# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4-r1 then corrected by me

EAPI=8

CRATES="
	aho-corasick@0.7.18
	autocfg@1.1.0
	bitflags@1.3.2
	bytesize@1.1.0
	cc@1.0.72
	cfg-if@1.0.0
	chrono@0.4.19
	lazy_static@1.4.0
	libc@0.2.117
	memchr@2.4.1
	memoffset@0.6.5
	minimal-lexical@0.2.1
	nix@0.23.1
	nom@7.1.0
	num-integer@0.1.44
	num-traits@0.2.14
	regex@1.5.4
	regex-syntax@0.6.25
	systemstat@0.1.10
	version_check@0.9.4
	winapi@0.3.9
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
"

inherit cargo

DESCRIPTION="🌲 A plant-based system fetch tool made with Rust. "
HOMEPAGE="https://github.com/angelofallars/treefetch"
SRC_URI="
	https://github.com/angelofallars/treefetch/archive/refs/tags/v${PV}.tar.gz -> ${P}.gh.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="Apache-2.0 MIT Unicode-DFS-2016 Unlicense"
SLOT="0"
KEYWORDS="~amd64 ~arm64"

# PATCHES=(
# 	"${FILESDIR}/update-cargo-lock.patch"
# )

# src_install() {
# 	cargo_src_install --path ./crates/${PN}
# }

QA_FLAGS_IGNORED="usr/bin/${PN}"
