# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.16.0

EAPI=8

CRATES="
	anstream@1.0.0
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.13
	anyhow@1.0.100
	cc@1.2.55
	cfg-if@1.0.4
	clap@4.6.1
	clap_builder@4.6.0
	clap_derive@4.6.1
	clap_lex@1.1.0
	colorchoice@1.0.4
	colored@3.1.1
	find-msvc-tools@0.1.9
	heck@0.5.0
	hidapi@2.6.4
	is_terminal_polyfill@1.70.2
	libc@0.2.180
	once_cell_polyfill@1.70.2
	pkg-config@0.3.32
	proc-macro2@1.0.106
	quote@1.0.46
	shlex@1.3.0
	strsim@0.11.1
	syn@2.0.118
	unicode-ident@1.0.22
	utf8parse@0.2.2
	windows-link@0.2.1
	windows-sys@0.48.0
	windows-sys@0.61.2
	windows-targets@0.48.5
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_msvc@0.48.5
	windows_i686_gnu@0.48.5
	windows_i686_msvc@0.48.5
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_msvc@0.48.5
"

inherit cargo

DESCRIPTION="CLI tool for Glorious wireless mice"
HOMEPAGE="https://github.com/dkbednarczyk/mxw"
SRC_URI="
	${CARGO_CRATE_URIS}
	https://github.com/dkbednarczyk/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz
"

LICENSE="GPL-3"
# Dependent crate licenses
LICENSE+=" MIT MPL-2.0 Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"
