diff --git i/Makefile w/Makefile
index 7d3056a..d8b1670 100644
--- i/Makefile
+++ w/Makefile
@@ -1,28 +1,27 @@
 CC=g++
-CCFLAGS=-O2 -Wall
 CFILES=game.cpp gamestate.cpp gui.cpp image.cpp main.cpp panel.cpp player.cpp resources.cpp screen.cpp sector.cpp sound.cpp tutorial.cpp utils.cpp TinyXML/tinyxml.cpp TinyXML/tinyxmlerror.cpp TinyXML/tinyxmlparser.cpp
 HFILES=game.h gamestate.h gui.h image.h panel.h player.h resources.h screen.h sector.h sound.h tutorial.h utils.h common.h stdafx.h TinyXML/tinyxml.h
 OFILES=game.o gamestate.o gui.o image.o panel.o player.o resources.o screen.o sector.o sound.o tutorial.o utils.o main.o TinyXML/tinyxml.o TinyXML/tinyxmlerror.o TinyXML/tinyxmlparser.o
 APP=gigalomania
 INC=`sdl2-config --cflags`
 LINKPATH=`sdl2-config --libs` -L/usr/X11R6/lib/ -L/usr/lib
 
 LIBS=-lSDL2_image -lSDL2_mixer
 
 all: $(APP)
 
 $(APP): $(OFILES) $(HFILES) $(CFILES)
-	$(CC) $(OFILES) $(CCFLAGS) $(LINKPATH) $(LIBS) -o $(APP)
+	$(CC) $(OFILES) ${CXXFLAGS} ${LDFLAGS} $(LINKPATH) $(LIBS) -o $(APP)
 
 .cpp.o:
-	$(CC) $(CCFLAGS) -O2 $(INC) -c $< -o $@
+	$(CC) ${CXXFLAGS} ${LDFLAGS} $(INC) -c $< -o $@
 
 # REMEMBER to update debian/dirs if the system directories that we use are changed!!!
 install: $(APP)
 	mkdir -p $(DESTDIR)/opt/gigalomania # -p so we don't fail if folder already exists
 	cp $(APP) $(DESTDIR)/opt/gigalomania
 	cp readme.html $(DESTDIR)/opt/gigalomania
 	cp -a gfx/ $(DESTDIR)/opt/gigalomania # -a need to copy permissions etc
 	cp -a islands/ $(DESTDIR)/opt/gigalomania
 	cp -a music/ $(DESTDIR)/opt/gigalomania
 	cp -a sound/ $(DESTDIR)/opt/gigalomania
