.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH COLORTAIL 1 "January  2, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
colortail \- log colorizer that makes log checking easier
.SH SYNOPSIS
.B colortail
.RI [ options ] [file...]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B colortail
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBcolortail\fP is basically tail but with support for colors. With the help of color 
config files you define what part of the output to print in which color.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-f, \-\-follow
Output appended data as the file grows.
.TP
.B \-k, \-\-config=file
.B     \-\-config=file1,file2,...
Color config files for the tail files. If only one config file it's global
otherwise one config file for each tail file.
.TP
.B \-n, \-\-lines=N
Output the last N lines, instead of last 10.
.TP
.B \-l
Display without colors.
.TP
.B \-q, \-\-quiet, \-\-silent
Never output headers giving file names.
.TP
.B \-v, \-\-version
Output version information and exit.
.TP
.br
.SH AUTHOR
colortail was written by Joakim Andersson <ja@joakimandersson.se> Copyright (C) 2009
.PP
This manual page was written by Elías Alejandro Año Mendoza <ealmdz@gmail.com>,
for the Debian project (and may be used by others).
