#!/sbin/openrc-run
# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="mautrix-linkedin daemon"
description="A Matrix-LinkedIN puppeting bridge"
module="mautrix_linkedin"

pidfile="/run/${RC_SVCNAME}.pid"
command="/usr/bin/mautrix-linkedin"
command_args="-c /etc/mautrix/${module}.yaml -r /var/lib/mautrix/linkedin/registration.yaml"
command_background=true
command_user="mautrix-linkedin:mautrix"

output_log="/var/log/mautrix/linkedin/daemon.log"
error_log="/var/log/mautrix/linkedin/daemon.log"

depend() {
	need net
}

start_pre() {
	checkpath -d -m 0755 -o "$command_user" /var/lib/mautrix/linkedin
	checkpath -f -m 0644 -o "$command_user" "$output_log"
}
