# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.14.0

EAPI=8

CRATES="
	autocfg@1.4.0
	byteorder@1.5.0
	cc@1.2.14
	cfg-if@1.0.0
	cmake@0.1.54
	crunchy@0.2.3
	darling@0.20.10
	darling_core@0.20.10
	darling_macro@0.20.10
	derive_builder@0.20.2
	derive_builder_core@0.20.2
	derive_builder_macro@0.20.2
	fnv@1.0.7
	half@2.4.1
	heck@0.5.0
	ident_case@1.0.1
	indoc@2.0.5
	jpegxl-rs@0.11.2+libjxl-0.11.1
	jpegxl-src@0.11.2
	jpegxl-sys@0.11.2+libjxl-0.11.1
	libc@0.2.169
	memoffset@0.9.1
	once_cell@1.20.3
	pkg-config@0.3.31
	portable-atomic@1.10.0
	proc-macro2@1.0.93
	pyo3-build-config@0.23.4
	pyo3-ffi@0.23.4
	pyo3-macros-backend@0.23.4
	pyo3-macros@0.23.4
	pyo3@0.23.4
	quote@1.0.38
	shlex@1.3.0
	strsim@0.11.1
	syn@2.0.98
	target-lexicon@0.12.16
	thiserror-impl@2.0.11
	thiserror@2.0.11
	unicode-ident@1.0.16
	unindent@0.2.3
"

DISTUTILS_USE_PEP517=maturin
PYTHON_COMPAT=( python3_{10..13} )

inherit cargo distutils-r1 pypi

DESCRIPTION="Pillow plugin for JPEG-XL, using Rust for bindings."
HOMEPAGE="
	https://github.com/Isotr0py/pillow-jpegxl-plugin
	https://pypi.org/project/pillow-jxl-plugin/
"
SRC_URI+=" ${CARGO_CRATE_URIS}"

LICENSE="GPL-3"
# Dependent crate licenses
LICENSE+=" Apache-2.0-with-LLVM-exceptions BSD GPL-3+ MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"

REPENDS="
	dev-python/packaging[${PYTHON_USEDEP}]
	dev-python/pillow[${PYTHON_USEDEP}]
"

# distutils_enable_tests pytest
