# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

inherit R-packages

DESCRIPTION='Convert Statistical Objects into Tidy Tibbles'
KEYWORDS="~amd64"
LICENSE='MIT'
DEPEND="
	dev-R/backports
	>=dev-R/dplyr-1.0.0
	dev-R/ellipsis
	>=dev-R/generics-0.0.2
	dev-R/glue
	dev-R/purrr
	dev-R/rlang
	dev-R/stringr
	>=dev-R/tibble-3.0.0
	>=dev-R/tidyr-1.0.0
	dev-R/ggplot2
"

SUGGESTED_PACKAGES="
	dev-R/AER
	dev-R/AUC
	dev-R/bbmle
	dev-R/betareg
	dev-R/biglm
	dev-R/binGroup
	dev-R/boot
	>=dev-R/btergm-1.10.6
	dev-R/car
	dev-R/caret
	dev-R/cluster
	dev-R/cmprsk
	dev-R/coda
	dev-R/covr
	dev-R/drc
	dev-R/e1071
	dev-R/emmeans
	dev-R/epiR
	>=dev-R/ergm-3.10.4
	>=dev-R/fixest-0.9.0
	>=dev-R/gam-1.15
	dev-R/gee
	dev-R/geepack
	dev-R/glmnet
	dev-R/glmnetUtils
	dev-R/gmm
	dev-R/Hmisc
	dev-R/irlba
	dev-R/interp
	dev-R/joineRML
	dev-R/Kendall
	dev-R/knitr
	dev-R/ks
	dev-R/Lahman
	dev-R/lavaan
	dev-R/leaps
	dev-R/lfe
	dev-R/lm-beta
	dev-R/lme4
	dev-R/lmodel2
	>=dev-R/lmtest-0.9.38
	dev-R/lsmeans
	dev-R/maps
	dev-R/maptools
	dev-R/margins
	dev-R/MASS
	dev-R/Matrix
	dev-R/mclust
	dev-R/mediation
	dev-R/metafor
	dev-R/mfx
	dev-R/mgcv
	dev-R/mlogit
	dev-R/modeldata
	dev-R/modeltests
	dev-R/muhaz
	dev-R/multcomp
	dev-R/network
	dev-R/nnet
	>=dev-R/orcutt-2.2
	dev-R/ordinal
	dev-R/plm
	dev-R/poLCA
	dev-R/psych
	dev-R/quantreg
	dev-R/rgeos
	dev-R/rmarkdown
	dev-R/robust
	dev-R/robustbase
	dev-R/rsample
	dev-R/sandwich
	dev-R/sp
	>=dev-R/spdep-1.1
	dev-R/spatialreg
	dev-R/speedglm
	dev-R/spelling
	dev-R/survey
	dev-R/survival
	dev-R/systemfit
	>=dev-R/testthat-2.1.0
	dev-R/tseries
	dev-R/vars
	dev-R/zoo
"
