# Copyright 2017-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=7

CRATES="
ansi_term-0.11.0
atty-0.2.11
autocfg-0.1.2
bitflags-1.0.4
byteorder-1.3.1
cfg-if-0.1.6
clap-2.32.0
cloudabi-0.0.3
fuchsia-cprng-0.1.1
heck-0.3.1
i3ipc-0.10.0
itoa-0.4.3
libc-0.2.49
log-0.4.6
proc-macro2-0.4.27
quote-0.6.11
rand-0.6.5
rand_chacha-0.1.1
rand_core-0.3.1
rand_core-0.4.0
rand_hc-0.1.0
rand_isaac-0.1.1
rand_jitter-0.1.3
rand_os-0.1.2
rand_pcg-0.1.2
rand_xorshift-0.1.1
rdrand-0.4.0
redox_syscall-0.1.51
redox_termios-0.1.1
remove_dir_all-0.5.1
ryu-0.2.7
serde-1.0.88
serde_json-1.0.38
strsim-0.7.0
structopt-0.2.15
structopt-derive-0.2.15
syn-0.15.29
tempfile-3.0.7
termion-1.5.1
textwrap-0.10.0
unicode-segmentation-1.2.1
unicode-width-0.1.5
unicode-xid-0.1.0
vec_map-0.8.1
winapi-0.3.6
winapi-i686-pc-windows-gnu-0.4.0
winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="A program that runs swaylock to a blurred screenshot of the desktop"
HOMEPAGE="https://github.com/cjbassi/swaylock-blur"
SRC_URI="
	https://github.com/cjbassi/swaylock-blur/archive/${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris ${CRATES})
"
RESTRICT="mirror"
LICENSE="MIT"
SLOT="0"
KEYWORDS=""  # Upstream has archived the project, use swaylock-effects instead
IUSE=""

DEPEND="
	gui-apps/swaylock
	media-video/ffmpeg
	gui-apps/grim
	gui-wm/sway
"
RDEPEND="${RDEPEND}"

pkg_postinst() {
	ewarn "gui-apps/swaylock-blur is deprecated"
	ewarn "in favor of gui-apps/swaylock-effects."
}
