--- a/code/Makefile	2021-04-12 01:42:10.792372462 +0200
+++ b/code/Makefile	2021-04-12 01:46:20.332391138 +0200
@@ -1,8 +1,6 @@
 DEST_DIR = 	../exec
 DEST=		${DEST_DIR}/chaco
-CC = 		gcc
 IFLAG =		-Imain
-CFLAGS =	-O2
 OFLAGS =	-O2
 
 FILES.c=	main/user_params.c main/interface.c main/main.c \
@@ -91,7 +89,7 @@
 
 
 ${DEST}:	${FILES.o} Makefile
-		${CC} ${OFLAGS} ${FILES.o} -lm -o ${DEST}
+		${CC} ${CFLAGS} -fPIE ${LDFLAGS} ${FILES.o} -lm -o ${DEST}
 
 lint:
 		lint ${IFLAG} ${FILES.c} -lm
@@ -103,4 +101,4 @@
 		rm -f */*.o ${DEST_DIR}/core
 
 .c.o:
-		${CC} -c ${IFLAG} ${CFLAGS} -o $*.o $*.c
+		${CC} -c ${IFLAG} ${CFLAGS} -fPIC -o $*.o $*.c
