# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

NPM_BUNDLE=1

inherit node

NPM_PACKAGES=(
@babel/code-frame/-/code-frame-7.12.11.tgz
@babel/helper-validator-identifier/-/helper-validator-identifier-7.15.7.tgz
@babel/highlight/-/highlight-7.14.5.tgz
ansi-styles/-/ansi-styles-3.2.1.tgz
chalk/-/chalk-2.4.2.tgz
color-convert/-/color-convert-1.9.3.tgz
color-name/-/color-name-1.1.3.tgz
escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
has-flag/-/has-flag-3.0.0.tgz
supports-color/-/supports-color-5.5.0.tgz
@bcoe/v8-coverage/-/v8-coverage-0.2.3.tgz
@eslint/eslintrc/-/eslintrc-0.4.3.tgz
@humanwhocodes/config-array/-/config-array-0.5.0.tgz
@humanwhocodes/object-schema/-/object-schema-1.2.0.tgz
@istanbuljs/schema/-/schema-0.1.3.tgz
@types/istanbul-lib-coverage/-/istanbul-lib-coverage-2.0.3.tgz
acorn/-/acorn-7.4.1.tgz
acorn-jsx/-/acorn-jsx-5.3.2.tgz
acorn-node/-/acorn-node-1.8.2.tgz
acorn-walk/-/acorn-walk-7.2.0.tgz
ajv/-/ajv-6.12.6.tgz
ansi-colors/-/ansi-colors-4.1.1.tgz
ansi-regex/-/ansi-regex-5.0.1.tgz
ansi-styles/-/ansi-styles-4.3.0.tgz
anymatch/-/anymatch-3.1.2.tgz
argparse/-/argparse-1.0.10.tgz
asn1/-/asn1-0.2.4.tgz
asn1.js/-/asn1.js-5.4.1.tgz
bn.js/-/bn.js-4.12.0.tgz
assert/-/assert-1.5.0.tgz
assert-plus/-/assert-plus-1.0.0.tgz
inherits/-/inherits-2.0.1.tgz
util/-/util-0.10.3.tgz
astral-regex/-/astral-regex-2.0.0.tgz
asynckit/-/asynckit-0.4.0.tgz
available-typed-arrays/-/available-typed-arrays-1.0.5.tgz
aws-sign2/-/aws-sign2-0.7.0.tgz
aws4/-/aws4-1.11.0.tgz
balanced-match/-/balanced-match-1.0.2.tgz
base64-js/-/base64-js-1.5.1.tgz
bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz
benchmark/-/benchmark-2.1.4.tgz
binary-extensions/-/binary-extensions-2.2.0.tgz
bn.js/-/bn.js-5.2.0.tgz
brace-expansion/-/brace-expansion-1.1.11.tgz
braces/-/braces-3.0.2.tgz
brorand/-/brorand-1.1.0.tgz
browser-pack/-/browser-pack-6.1.0.tgz
browser-resolve/-/browser-resolve-2.0.0.tgz
browserify/-/browserify-17.0.0.tgz
browserify-aes/-/browserify-aes-1.2.0.tgz
browserify-cipher/-/browserify-cipher-1.0.1.tgz
browserify-des/-/browserify-des-1.0.2.tgz
browserify-rsa/-/browserify-rsa-4.1.0.tgz
browserify-sign/-/browserify-sign-4.2.1.tgz
readable-stream/-/readable-stream-3.6.0.tgz
browserify-zlib/-/browserify-zlib-0.2.0.tgz
buffer/-/buffer-5.2.1.tgz
buffer-from/-/buffer-from-1.1.2.tgz
buffer-xor/-/buffer-xor-1.0.3.tgz
builtin-status-codes/-/builtin-status-codes-3.0.0.tgz
c8/-/c8-7.9.0.tgz
cached-path-relative/-/cached-path-relative-1.0.2.tgz
call-bind/-/call-bind-1.0.2.tgz
callsites/-/callsites-3.1.0.tgz
caseless/-/caseless-0.12.0.tgz
chalk/-/chalk-4.1.2.tgz
chokidar/-/chokidar-3.5.2.tgz
cipher-base/-/cipher-base-1.0.4.tgz
cliui/-/cliui-7.0.4.tgz
color-convert/-/color-convert-2.0.1.tgz
color-name/-/color-name-1.1.4.tgz
combine-source-map/-/combine-source-map-0.8.0.tgz
combined-stream/-/combined-stream-1.0.8.tgz
concat-map/-/concat-map-0.0.1.tgz
concat-stream/-/concat-stream-1.6.2.tgz
console-browserify/-/console-browserify-1.2.0.tgz
constants-browserify/-/constants-browserify-1.0.0.tgz
convert-source-map/-/convert-source-map-1.1.3.tgz
core-util-is/-/core-util-is-1.0.3.tgz
coveralls/-/coveralls-3.1.1.tgz
create-ecdh/-/create-ecdh-4.0.4.tgz
bn.js/-/bn.js-4.12.0.tgz
create-hash/-/create-hash-1.2.0.tgz
create-hmac/-/create-hmac-1.1.7.tgz
cross-spawn/-/cross-spawn-7.0.3.tgz
crypto-browserify/-/crypto-browserify-3.12.0.tgz
dash-ast/-/dash-ast-1.0.0.tgz
dashdash/-/dashdash-1.14.1.tgz
debug/-/debug-4.3.2.tgz
deep-equal/-/deep-equal-2.0.5.tgz
isarray/-/isarray-2.0.5.tgz
deep-is/-/deep-is-0.1.4.tgz
define-properties/-/define-properties-1.1.3.tgz
defined/-/defined-1.0.0.tgz
delayed-stream/-/delayed-stream-1.0.0.tgz
deps-sort/-/deps-sort-2.0.1.tgz
des.js/-/des.js-1.0.1.tgz
detective/-/detective-5.2.0.tgz
diffie-hellman/-/diffie-hellman-5.0.3.tgz
bn.js/-/bn.js-4.12.0.tgz
doctrine/-/doctrine-3.0.0.tgz
domain-browser/-/domain-browser-1.2.0.tgz
dotignore/-/dotignore-0.1.2.tgz
duplexer2/-/duplexer2-0.1.4.tgz
ecc-jsbn/-/ecc-jsbn-0.1.2.tgz
elliptic/-/elliptic-6.5.4.tgz
bn.js/-/bn.js-4.12.0.tgz
emoji-regex/-/emoji-regex-8.0.0.tgz
enquirer/-/enquirer-2.3.6.tgz
es-abstract/-/es-abstract-1.19.0.tgz
es-get-iterator/-/es-get-iterator-1.1.2.tgz
isarray/-/isarray-2.0.5.tgz
es-to-primitive/-/es-to-primitive-1.2.1.tgz
escalade/-/escalade-3.1.1.tgz
escape-string-regexp/-/escape-string-regexp-4.0.0.tgz
eslint/-/eslint-7.32.0.tgz
eslint-config-mourner/-/eslint-config-mourner-2.0.3.tgz
eslint-scope/-/eslint-scope-5.1.1.tgz
eslint-utils/-/eslint-utils-2.1.0.tgz
eslint-visitor-keys/-/eslint-visitor-keys-1.3.0.tgz
eslint-visitor-keys/-/eslint-visitor-keys-2.1.0.tgz
espree/-/espree-7.3.1.tgz
eslint-visitor-keys/-/eslint-visitor-keys-1.3.0.tgz
esprima/-/esprima-4.0.1.tgz
esquery/-/esquery-1.4.0.tgz
estraverse/-/estraverse-5.2.0.tgz
esrecurse/-/esrecurse-4.3.0.tgz
estraverse/-/estraverse-5.2.0.tgz
estraverse/-/estraverse-4.3.0.tgz
esutils/-/esutils-2.0.3.tgz
events/-/events-3.3.0.tgz
evp_bytestokey/-/evp_bytestokey-1.0.3.tgz
extend/-/extend-3.0.2.tgz
extsprintf/-/extsprintf-1.3.0.tgz
fast-deep-equal/-/fast-deep-equal-3.1.3.tgz
fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz
fast-levenshtein/-/fast-levenshtein-2.0.6.tgz
fast-safe-stringify/-/fast-safe-stringify-2.1.1.tgz
file-entry-cache/-/file-entry-cache-6.0.1.tgz
fill-range/-/fill-range-7.0.1.tgz
find-up/-/find-up-5.0.0.tgz
flat-cache/-/flat-cache-3.0.4.tgz
flatted/-/flatted-3.2.2.tgz
for-each/-/for-each-0.3.3.tgz
foreach/-/foreach-2.0.5.tgz
foreground-child/-/foreground-child-2.0.0.tgz
forever-agent/-/forever-agent-0.6.1.tgz
form-data/-/form-data-2.3.3.tgz
fs.realpath/-/fs.realpath-1.0.0.tgz
fsevents/-/fsevents-2.3.2.tgz
function-bind/-/function-bind-1.1.1.tgz
functional-red-black-tree/-/functional-red-black-tree-1.0.1.tgz
get-assigned-identifiers/-/get-assigned-identifiers-1.2.0.tgz
get-caller-file/-/get-caller-file-2.0.5.tgz
get-intrinsic/-/get-intrinsic-1.1.1.tgz
get-package-type/-/get-package-type-0.1.0.tgz
get-symbol-description/-/get-symbol-description-1.0.0.tgz
getpass/-/getpass-0.1.7.tgz
glob/-/glob-7.2.0.tgz
glob-parent/-/glob-parent-5.1.2.tgz
globals/-/globals-13.11.0.tgz
har-schema/-/har-schema-2.0.0.tgz
har-validator/-/har-validator-5.1.5.tgz
has/-/has-1.0.3.tgz
has-bigints/-/has-bigints-1.0.1.tgz
has-dynamic-import/-/has-dynamic-import-2.0.0.tgz
has-flag/-/has-flag-4.0.0.tgz
has-symbols/-/has-symbols-1.0.2.tgz
has-tostringtag/-/has-tostringtag-1.0.0.tgz
hash-base/-/hash-base-3.1.0.tgz
readable-stream/-/readable-stream-3.6.0.tgz
hash.js/-/hash.js-1.1.7.tgz
hmac-drbg/-/hmac-drbg-1.0.1.tgz
html-escaper/-/html-escaper-2.0.2.tgz
htmlescape/-/htmlescape-1.1.1.tgz
http-signature/-/http-signature-1.2.0.tgz
https-browserify/-/https-browserify-1.0.0.tgz
ieee754/-/ieee754-1.2.1.tgz
ignore/-/ignore-4.0.6.tgz
import-fresh/-/import-fresh-3.3.0.tgz
imurmurhash/-/imurmurhash-0.1.4.tgz
inflight/-/inflight-1.0.6.tgz
inherits/-/inherits-2.0.4.tgz
inline-source-map/-/inline-source-map-0.6.2.tgz
insert-module-globals/-/insert-module-globals-7.2.1.tgz
internal-slot/-/internal-slot-1.0.3.tgz
is-arguments/-/is-arguments-1.1.1.tgz
is-bigint/-/is-bigint-1.0.4.tgz
is-binary-path/-/is-binary-path-2.1.0.tgz
is-boolean-object/-/is-boolean-object-1.1.2.tgz
is-buffer/-/is-buffer-1.1.6.tgz
is-callable/-/is-callable-1.2.4.tgz
is-core-module/-/is-core-module-2.7.0.tgz
is-date-object/-/is-date-object-1.0.5.tgz
is-extglob/-/is-extglob-2.1.1.tgz
is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz
is-generator-function/-/is-generator-function-1.0.10.tgz
is-glob/-/is-glob-4.0.3.tgz
is-map/-/is-map-2.0.2.tgz
is-negative-zero/-/is-negative-zero-2.0.1.tgz
is-number/-/is-number-7.0.0.tgz
is-number-object/-/is-number-object-1.0.6.tgz
is-regex/-/is-regex-1.1.4.tgz
is-set/-/is-set-2.0.2.tgz
is-shared-array-buffer/-/is-shared-array-buffer-1.0.1.tgz
is-string/-/is-string-1.0.7.tgz
is-symbol/-/is-symbol-1.0.4.tgz
is-typed-array/-/is-typed-array-1.1.8.tgz
is-typedarray/-/is-typedarray-1.0.0.tgz
is-weakmap/-/is-weakmap-2.0.1.tgz
is-weakref/-/is-weakref-1.0.1.tgz
is-weakset/-/is-weakset-2.0.1.tgz
isarray/-/isarray-1.0.0.tgz
isexe/-/isexe-2.0.0.tgz
isstream/-/isstream-0.1.2.tgz
istanbul-lib-coverage/-/istanbul-lib-coverage-3.0.1.tgz
istanbul-lib-report/-/istanbul-lib-report-3.0.0.tgz
istanbul-reports/-/istanbul-reports-3.0.2.tgz
js-tokens/-/js-tokens-4.0.0.tgz
js-yaml/-/js-yaml-3.14.1.tgz
jsbn/-/jsbn-0.1.1.tgz
json-schema/-/json-schema-0.2.3.tgz
json-schema-traverse/-/json-schema-traverse-0.4.1.tgz
json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz
json-stringify-safe/-/json-stringify-safe-5.0.1.tgz
jsonparse/-/jsonparse-1.3.1.tgz
JSONStream/-/JSONStream-1.3.5.tgz
jsprim/-/jsprim-1.4.1.tgz
labeled-stream-splicer/-/labeled-stream-splicer-2.0.2.tgz
lcov-parse/-/lcov-parse-1.0.0.tgz
levn/-/levn-0.4.1.tgz
locate-path/-/locate-path-6.0.0.tgz
lodash/-/lodash-4.17.21.tgz
lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz
lodash.memoize/-/lodash.memoize-3.0.4.tgz
lodash.merge/-/lodash.merge-4.6.2.tgz
lodash.truncate/-/lodash.truncate-4.4.2.tgz
log-driver/-/log-driver-1.2.7.tgz
lru-cache/-/lru-cache-6.0.0.tgz
make-dir/-/make-dir-3.1.0.tgz
semver/-/semver-6.3.0.tgz
md5.js/-/md5.js-1.3.5.tgz
miller-rabin/-/miller-rabin-4.0.1.tgz
bn.js/-/bn.js-4.12.0.tgz
mime-db/-/mime-db-1.49.0.tgz
mime-types/-/mime-types-2.1.32.tgz
minimalistic-assert/-/minimalistic-assert-1.0.1.tgz
minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz
minimatch/-/minimatch-3.0.4.tgz
minimist/-/minimist-1.2.5.tgz
mkdirp/-/mkdirp-1.0.4.tgz
mkdirp-classic/-/mkdirp-classic-0.5.3.tgz
module-deps/-/module-deps-6.2.3.tgz
ms/-/ms-2.1.2.tgz
natural-compare/-/natural-compare-1.4.0.tgz
normalize-path/-/normalize-path-3.0.0.tgz
oauth-sign/-/oauth-sign-0.9.0.tgz
object-assign/-/object-assign-4.1.1.tgz
object-inspect/-/object-inspect-1.11.0.tgz
object-is/-/object-is-1.1.5.tgz
object-keys/-/object-keys-1.1.1.tgz
object.assign/-/object.assign-4.1.2.tgz
once/-/once-1.4.0.tgz
optionator/-/optionator-0.9.1.tgz
os-browserify/-/os-browserify-0.3.0.tgz
outpipe/-/outpipe-1.1.1.tgz
p-limit/-/p-limit-3.1.0.tgz
p-locate/-/p-locate-5.0.0.tgz
pako/-/pako-1.0.11.tgz
parent-module/-/parent-module-1.0.1.tgz
parents/-/parents-1.0.1.tgz
parse-asn1/-/parse-asn1-5.1.6.tgz
path-browserify/-/path-browserify-1.0.1.tgz
path-exists/-/path-exists-4.0.0.tgz
path-is-absolute/-/path-is-absolute-1.0.1.tgz
path-key/-/path-key-3.1.1.tgz
path-parse/-/path-parse-1.0.7.tgz
path-platform/-/path-platform-0.11.15.tgz
pbkdf2/-/pbkdf2-3.1.2.tgz
performance-now/-/performance-now-2.1.0.tgz
picomatch/-/picomatch-2.3.0.tgz
platform/-/platform-1.3.6.tgz
prelude-ls/-/prelude-ls-1.2.1.tgz
process/-/process-0.11.10.tgz
process-nextick-args/-/process-nextick-args-2.0.1.tgz
progress/-/progress-2.0.3.tgz
psl/-/psl-1.8.0.tgz
public-encrypt/-/public-encrypt-4.0.3.tgz
bn.js/-/bn.js-4.12.0.tgz
punycode/-/punycode-1.4.1.tgz
qs/-/qs-6.5.2.tgz
querystring/-/querystring-0.2.0.tgz
querystring-es3/-/querystring-es3-0.2.1.tgz
randombytes/-/randombytes-2.1.0.tgz
randomfill/-/randomfill-1.0.4.tgz
read-only-stream/-/read-only-stream-2.0.0.tgz
readable-stream/-/readable-stream-2.3.7.tgz
safe-buffer/-/safe-buffer-5.1.2.tgz
string_decoder/-/string_decoder-1.1.1.tgz
readdirp/-/readdirp-3.6.0.tgz
regexp.prototype.flags/-/regexp.prototype.flags-1.3.1.tgz
regexpp/-/regexpp-3.2.0.tgz
request/-/request-2.88.2.tgz
require-directory/-/require-directory-2.1.1.tgz
require-from-string/-/require-from-string-2.0.2.tgz
resolve/-/resolve-1.20.0.tgz
resolve-from/-/resolve-from-4.0.0.tgz
resumer/-/resumer-0.0.0.tgz
rimraf/-/rimraf-3.0.2.tgz
ripemd160/-/ripemd160-2.0.2.tgz
safe-buffer/-/safe-buffer-5.2.1.tgz
safer-buffer/-/safer-buffer-2.1.2.tgz
semver/-/semver-7.3.5.tgz
sha.js/-/sha.js-2.4.11.tgz
shasum-object/-/shasum-object-1.0.0.tgz
shebang-command/-/shebang-command-2.0.0.tgz
shebang-regex/-/shebang-regex-3.0.0.tgz
shell-quote/-/shell-quote-1.7.2.tgz
side-channel/-/side-channel-1.0.4.tgz
signal-exit/-/signal-exit-3.0.5.tgz
simple-concat/-/simple-concat-1.0.1.tgz
slice-ansi/-/slice-ansi-4.0.0.tgz
source-map/-/source-map-0.5.7.tgz
sprintf-js/-/sprintf-js-1.0.3.tgz
sshpk/-/sshpk-1.16.1.tgz
stream-browserify/-/stream-browserify-3.0.0.tgz
readable-stream/-/readable-stream-3.6.0.tgz
stream-combiner2/-/stream-combiner2-1.1.1.tgz
stream-http/-/stream-http-3.2.0.tgz
readable-stream/-/readable-stream-3.6.0.tgz
stream-splicer/-/stream-splicer-2.0.1.tgz
string_decoder/-/string_decoder-1.3.0.tgz
string-width/-/string-width-4.2.3.tgz
string.prototype.trim/-/string.prototype.trim-1.2.4.tgz
string.prototype.trimend/-/string.prototype.trimend-1.0.4.tgz
string.prototype.trimstart/-/string.prototype.trimstart-1.0.4.tgz
strip-ansi/-/strip-ansi-6.0.1.tgz
strip-json-comments/-/strip-json-comments-3.1.1.tgz
subarg/-/subarg-1.0.0.tgz
supports-color/-/supports-color-7.2.0.tgz
syntax-error/-/syntax-error-1.4.0.tgz
table/-/table-6.7.2.tgz
ajv/-/ajv-8.6.3.tgz
json-schema-traverse/-/json-schema-traverse-1.0.0.tgz
tape/-/tape-5.3.1.tgz
resolve/-/resolve-2.0.0-next.3.tgz
test-exclude/-/test-exclude-6.0.0.tgz
text-table/-/text-table-0.2.0.tgz
through/-/through-2.3.8.tgz
through2/-/through2-2.0.5.tgz
timers-browserify/-/timers-browserify-1.4.2.tgz
to-regex-range/-/to-regex-range-5.0.1.tgz
tough-cookie/-/tough-cookie-2.5.0.tgz
punycode/-/punycode-2.1.1.tgz
tty-browserify/-/tty-browserify-0.0.1.tgz
tunnel-agent/-/tunnel-agent-0.6.0.tgz
tweetnacl/-/tweetnacl-0.14.5.tgz
type-check/-/type-check-0.4.0.tgz
type-fest/-/type-fest-0.20.2.tgz
typedarray/-/typedarray-0.0.6.tgz
uglify-js/-/uglify-js-3.14.2.tgz
umd/-/umd-3.0.3.tgz
unbox-primitive/-/unbox-primitive-1.0.1.tgz
undeclared-identifiers/-/undeclared-identifiers-1.1.3.tgz
uri-js/-/uri-js-4.4.1.tgz
punycode/-/punycode-2.1.1.tgz
url/-/url-0.11.0.tgz
punycode/-/punycode-1.3.2.tgz
util/-/util-0.12.4.tgz
util-deprecate/-/util-deprecate-1.0.2.tgz
uuid/-/uuid-3.4.0.tgz
v8-compile-cache/-/v8-compile-cache-2.3.0.tgz
v8-to-istanbul/-/v8-to-istanbul-8.1.0.tgz
convert-source-map/-/convert-source-map-1.8.0.tgz
safe-buffer/-/safe-buffer-5.1.2.tgz
source-map/-/source-map-0.7.3.tgz
verror/-/verror-1.10.0.tgz
core-util-is/-/core-util-is-1.0.2.tgz
vm-browserify/-/vm-browserify-1.1.2.tgz
watchify/-/watchify-4.0.0.tgz
readable-stream/-/readable-stream-3.6.0.tgz
through2/-/through2-4.0.2.tgz
which/-/which-2.0.2.tgz
which-boxed-primitive/-/which-boxed-primitive-1.0.2.tgz
which-collection/-/which-collection-1.0.1.tgz
which-typed-array/-/which-typed-array-1.1.7.tgz
word-wrap/-/word-wrap-1.2.3.tgz
wrap-ansi/-/wrap-ansi-7.0.0.tgz
wrappy/-/wrappy-1.0.2.tgz
xtend/-/xtend-4.0.2.tgz
y18n/-/y18n-5.0.8.tgz
yallist/-/yallist-4.0.0.tgz
yargs/-/yargs-16.2.0.tgz
yargs-parser/-/yargs-parser-20.2.9.tgz
yocto-queue/-/yocto-queue-0.1.0.tgz
@babel/code-frame/-/code-frame-7.12.11.tgz
@babel/helper-validator-identifier/-/helper-validator-identifier-7.15.7.tgz
@babel/highlight/-/highlight-7.14.5.tgz
ansi-styles/-/ansi-styles-3.2.1.tgz
chalk/-/chalk-2.4.2.tgz
color-convert/-/color-convert-1.9.3.tgz
color-name/-/color-name-1.1.3.tgz
escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
has-flag/-/has-flag-3.0.0.tgz
supports-color/-/supports-color-5.5.0.tgz
@bcoe/v8-coverage/-/v8-coverage-0.2.3.tgz
@eslint/eslintrc/-/eslintrc-0.4.3.tgz
@humanwhocodes/config-array/-/config-array-0.5.0.tgz
@humanwhocodes/object-schema/-/object-schema-1.2.0.tgz
@istanbuljs/schema/-/schema-0.1.3.tgz
@types/istanbul-lib-coverage/-/istanbul-lib-coverage-2.0.3.tgz
acorn/-/acorn-7.4.1.tgz
acorn-jsx/-/acorn-jsx-5.3.2.tgz
acorn-node/-/acorn-node-1.8.2.tgz
acorn-walk/-/acorn-walk-7.2.0.tgz
ajv/-/ajv-6.12.6.tgz
ansi-colors/-/ansi-colors-4.1.1.tgz
ansi-regex/-/ansi-regex-5.0.1.tgz
ansi-styles/-/ansi-styles-4.3.0.tgz
anymatch/-/anymatch-3.1.2.tgz
argparse/-/argparse-1.0.10.tgz
asn1/-/asn1-0.2.4.tgz
asn1.js/-/asn1.js-5.4.1.tgz
bn.js/-/bn.js-4.12.0.tgz
assert/-/assert-1.5.0.tgz
inherits/-/inherits-2.0.1.tgz
util/-/util-0.10.3.tgz
assert-plus/-/assert-plus-1.0.0.tgz
astral-regex/-/astral-regex-2.0.0.tgz
asynckit/-/asynckit-0.4.0.tgz
available-typed-arrays/-/available-typed-arrays-1.0.5.tgz
aws-sign2/-/aws-sign2-0.7.0.tgz
aws4/-/aws4-1.11.0.tgz
balanced-match/-/balanced-match-1.0.2.tgz
base64-js/-/base64-js-1.5.1.tgz
bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz
benchmark/-/benchmark-2.1.4.tgz
binary-extensions/-/binary-extensions-2.2.0.tgz
bn.js/-/bn.js-5.2.0.tgz
brace-expansion/-/brace-expansion-1.1.11.tgz
braces/-/braces-3.0.2.tgz
brorand/-/brorand-1.1.0.tgz
browser-pack/-/browser-pack-6.1.0.tgz
browser-resolve/-/browser-resolve-2.0.0.tgz
browserify/-/browserify-17.0.0.tgz
browserify-aes/-/browserify-aes-1.2.0.tgz
browserify-cipher/-/browserify-cipher-1.0.1.tgz
browserify-des/-/browserify-des-1.0.2.tgz
browserify-rsa/-/browserify-rsa-4.1.0.tgz
browserify-sign/-/browserify-sign-4.2.1.tgz
readable-stream/-/readable-stream-3.6.0.tgz
browserify-zlib/-/browserify-zlib-0.2.0.tgz
buffer/-/buffer-5.2.1.tgz
buffer-from/-/buffer-from-1.1.2.tgz
buffer-xor/-/buffer-xor-1.0.3.tgz
builtin-status-codes/-/builtin-status-codes-3.0.0.tgz
c8/-/c8-7.9.0.tgz
cached-path-relative/-/cached-path-relative-1.0.2.tgz
call-bind/-/call-bind-1.0.2.tgz
callsites/-/callsites-3.1.0.tgz
caseless/-/caseless-0.12.0.tgz
chalk/-/chalk-4.1.2.tgz
chokidar/-/chokidar-3.5.2.tgz
cipher-base/-/cipher-base-1.0.4.tgz
cliui/-/cliui-7.0.4.tgz
color-convert/-/color-convert-2.0.1.tgz
color-name/-/color-name-1.1.4.tgz
combine-source-map/-/combine-source-map-0.8.0.tgz
combined-stream/-/combined-stream-1.0.8.tgz
concat-map/-/concat-map-0.0.1.tgz
concat-stream/-/concat-stream-1.6.2.tgz
console-browserify/-/console-browserify-1.2.0.tgz
constants-browserify/-/constants-browserify-1.0.0.tgz
convert-source-map/-/convert-source-map-1.1.3.tgz
core-util-is/-/core-util-is-1.0.3.tgz
coveralls/-/coveralls-3.1.1.tgz
create-ecdh/-/create-ecdh-4.0.4.tgz
bn.js/-/bn.js-4.12.0.tgz
create-hash/-/create-hash-1.2.0.tgz
create-hmac/-/create-hmac-1.1.7.tgz
cross-spawn/-/cross-spawn-7.0.3.tgz
crypto-browserify/-/crypto-browserify-3.12.0.tgz
dash-ast/-/dash-ast-1.0.0.tgz
dashdash/-/dashdash-1.14.1.tgz
debug/-/debug-4.3.2.tgz
deep-equal/-/deep-equal-2.0.5.tgz
isarray/-/isarray-2.0.5.tgz
deep-is/-/deep-is-0.1.4.tgz
define-properties/-/define-properties-1.1.3.tgz
defined/-/defined-1.0.0.tgz
delayed-stream/-/delayed-stream-1.0.0.tgz
deps-sort/-/deps-sort-2.0.1.tgz
des.js/-/des.js-1.0.1.tgz
detective/-/detective-5.2.0.tgz
diffie-hellman/-/diffie-hellman-5.0.3.tgz
bn.js/-/bn.js-4.12.0.tgz
doctrine/-/doctrine-3.0.0.tgz
domain-browser/-/domain-browser-1.2.0.tgz
dotignore/-/dotignore-0.1.2.tgz
duplexer2/-/duplexer2-0.1.4.tgz
ecc-jsbn/-/ecc-jsbn-0.1.2.tgz
elliptic/-/elliptic-6.5.4.tgz
bn.js/-/bn.js-4.12.0.tgz
emoji-regex/-/emoji-regex-8.0.0.tgz
enquirer/-/enquirer-2.3.6.tgz
es-abstract/-/es-abstract-1.19.0.tgz
es-get-iterator/-/es-get-iterator-1.1.2.tgz
isarray/-/isarray-2.0.5.tgz
es-to-primitive/-/es-to-primitive-1.2.1.tgz
escalade/-/escalade-3.1.1.tgz
escape-string-regexp/-/escape-string-regexp-4.0.0.tgz
eslint/-/eslint-7.32.0.tgz
eslint-config-mourner/-/eslint-config-mourner-2.0.3.tgz
eslint-scope/-/eslint-scope-5.1.1.tgz
eslint-utils/-/eslint-utils-2.1.0.tgz
eslint-visitor-keys/-/eslint-visitor-keys-1.3.0.tgz
eslint-visitor-keys/-/eslint-visitor-keys-2.1.0.tgz
espree/-/espree-7.3.1.tgz
eslint-visitor-keys/-/eslint-visitor-keys-1.3.0.tgz
esprima/-/esprima-4.0.1.tgz
esquery/-/esquery-1.4.0.tgz
estraverse/-/estraverse-5.2.0.tgz
esrecurse/-/esrecurse-4.3.0.tgz
estraverse/-/estraverse-5.2.0.tgz
estraverse/-/estraverse-4.3.0.tgz
esutils/-/esutils-2.0.3.tgz
events/-/events-3.3.0.tgz
evp_bytestokey/-/evp_bytestokey-1.0.3.tgz
extend/-/extend-3.0.2.tgz
extsprintf/-/extsprintf-1.3.0.tgz
fast-deep-equal/-/fast-deep-equal-3.1.3.tgz
fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz
fast-levenshtein/-/fast-levenshtein-2.0.6.tgz
fast-safe-stringify/-/fast-safe-stringify-2.1.1.tgz
file-entry-cache/-/file-entry-cache-6.0.1.tgz
fill-range/-/fill-range-7.0.1.tgz
find-up/-/find-up-5.0.0.tgz
flat-cache/-/flat-cache-3.0.4.tgz
flatted/-/flatted-3.2.2.tgz
for-each/-/for-each-0.3.3.tgz
foreach/-/foreach-2.0.5.tgz
foreground-child/-/foreground-child-2.0.0.tgz
forever-agent/-/forever-agent-0.6.1.tgz
form-data/-/form-data-2.3.3.tgz
fs.realpath/-/fs.realpath-1.0.0.tgz
fsevents/-/fsevents-2.3.2.tgz
function-bind/-/function-bind-1.1.1.tgz
functional-red-black-tree/-/functional-red-black-tree-1.0.1.tgz
get-assigned-identifiers/-/get-assigned-identifiers-1.2.0.tgz
get-caller-file/-/get-caller-file-2.0.5.tgz
get-intrinsic/-/get-intrinsic-1.1.1.tgz
get-package-type/-/get-package-type-0.1.0.tgz
get-symbol-description/-/get-symbol-description-1.0.0.tgz
getpass/-/getpass-0.1.7.tgz
glob/-/glob-7.2.0.tgz
glob-parent/-/glob-parent-5.1.2.tgz
globals/-/globals-13.11.0.tgz
har-schema/-/har-schema-2.0.0.tgz
har-validator/-/har-validator-5.1.5.tgz
has/-/has-1.0.3.tgz
has-bigints/-/has-bigints-1.0.1.tgz
has-dynamic-import/-/has-dynamic-import-2.0.0.tgz
has-flag/-/has-flag-4.0.0.tgz
has-symbols/-/has-symbols-1.0.2.tgz
has-tostringtag/-/has-tostringtag-1.0.0.tgz
hash-base/-/hash-base-3.1.0.tgz
readable-stream/-/readable-stream-3.6.0.tgz
hash.js/-/hash.js-1.1.7.tgz
hmac-drbg/-/hmac-drbg-1.0.1.tgz
html-escaper/-/html-escaper-2.0.2.tgz
htmlescape/-/htmlescape-1.1.1.tgz
http-signature/-/http-signature-1.2.0.tgz
https-browserify/-/https-browserify-1.0.0.tgz
ieee754/-/ieee754-1.2.1.tgz
ignore/-/ignore-4.0.6.tgz
import-fresh/-/import-fresh-3.3.0.tgz
imurmurhash/-/imurmurhash-0.1.4.tgz
inflight/-/inflight-1.0.6.tgz
inherits/-/inherits-2.0.4.tgz
inline-source-map/-/inline-source-map-0.6.2.tgz
insert-module-globals/-/insert-module-globals-7.2.1.tgz
internal-slot/-/internal-slot-1.0.3.tgz
is-arguments/-/is-arguments-1.1.1.tgz
is-bigint/-/is-bigint-1.0.4.tgz
is-binary-path/-/is-binary-path-2.1.0.tgz
is-boolean-object/-/is-boolean-object-1.1.2.tgz
is-buffer/-/is-buffer-1.1.6.tgz
is-callable/-/is-callable-1.2.4.tgz
is-core-module/-/is-core-module-2.7.0.tgz
is-date-object/-/is-date-object-1.0.5.tgz
is-extglob/-/is-extglob-2.1.1.tgz
is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz
is-generator-function/-/is-generator-function-1.0.10.tgz
is-glob/-/is-glob-4.0.3.tgz
is-map/-/is-map-2.0.2.tgz
is-negative-zero/-/is-negative-zero-2.0.1.tgz
is-number/-/is-number-7.0.0.tgz
is-number-object/-/is-number-object-1.0.6.tgz
is-regex/-/is-regex-1.1.4.tgz
is-set/-/is-set-2.0.2.tgz
is-shared-array-buffer/-/is-shared-array-buffer-1.0.1.tgz
is-string/-/is-string-1.0.7.tgz
is-symbol/-/is-symbol-1.0.4.tgz
is-typed-array/-/is-typed-array-1.1.8.tgz
is-typedarray/-/is-typedarray-1.0.0.tgz
is-weakmap/-/is-weakmap-2.0.1.tgz
is-weakref/-/is-weakref-1.0.1.tgz
is-weakset/-/is-weakset-2.0.1.tgz
isarray/-/isarray-1.0.0.tgz
isexe/-/isexe-2.0.0.tgz
isstream/-/isstream-0.1.2.tgz
istanbul-lib-coverage/-/istanbul-lib-coverage-3.0.1.tgz
istanbul-lib-report/-/istanbul-lib-report-3.0.0.tgz
istanbul-reports/-/istanbul-reports-3.0.2.tgz
js-tokens/-/js-tokens-4.0.0.tgz
js-yaml/-/js-yaml-3.14.1.tgz
jsbn/-/jsbn-0.1.1.tgz
json-schema/-/json-schema-0.2.3.tgz
json-schema-traverse/-/json-schema-traverse-0.4.1.tgz
json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz
json-stringify-safe/-/json-stringify-safe-5.0.1.tgz
jsonparse/-/jsonparse-1.3.1.tgz
JSONStream/-/JSONStream-1.3.5.tgz
jsprim/-/jsprim-1.4.1.tgz
labeled-stream-splicer/-/labeled-stream-splicer-2.0.2.tgz
lcov-parse/-/lcov-parse-1.0.0.tgz
levn/-/levn-0.4.1.tgz
locate-path/-/locate-path-6.0.0.tgz
lodash/-/lodash-4.17.21.tgz
lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz
lodash.memoize/-/lodash.memoize-3.0.4.tgz
lodash.merge/-/lodash.merge-4.6.2.tgz
lodash.truncate/-/lodash.truncate-4.4.2.tgz
log-driver/-/log-driver-1.2.7.tgz
lru-cache/-/lru-cache-6.0.0.tgz
make-dir/-/make-dir-3.1.0.tgz
semver/-/semver-6.3.0.tgz
md5.js/-/md5.js-1.3.5.tgz
miller-rabin/-/miller-rabin-4.0.1.tgz
bn.js/-/bn.js-4.12.0.tgz
mime-db/-/mime-db-1.49.0.tgz
mime-types/-/mime-types-2.1.32.tgz
minimalistic-assert/-/minimalistic-assert-1.0.1.tgz
minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz
minimatch/-/minimatch-3.0.4.tgz
minimist/-/minimist-1.2.5.tgz
mkdirp/-/mkdirp-1.0.4.tgz
mkdirp-classic/-/mkdirp-classic-0.5.3.tgz
module-deps/-/module-deps-6.2.3.tgz
ms/-/ms-2.1.2.tgz
natural-compare/-/natural-compare-1.4.0.tgz
normalize-path/-/normalize-path-3.0.0.tgz
oauth-sign/-/oauth-sign-0.9.0.tgz
object-assign/-/object-assign-4.1.1.tgz
object-inspect/-/object-inspect-1.11.0.tgz
object-is/-/object-is-1.1.5.tgz
object-keys/-/object-keys-1.1.1.tgz
object.assign/-/object.assign-4.1.2.tgz
once/-/once-1.4.0.tgz
optionator/-/optionator-0.9.1.tgz
os-browserify/-/os-browserify-0.3.0.tgz
outpipe/-/outpipe-1.1.1.tgz
p-limit/-/p-limit-3.1.0.tgz
p-locate/-/p-locate-5.0.0.tgz
pako/-/pako-1.0.11.tgz
parent-module/-/parent-module-1.0.1.tgz
parents/-/parents-1.0.1.tgz
parse-asn1/-/parse-asn1-5.1.6.tgz
path-browserify/-/path-browserify-1.0.1.tgz
path-exists/-/path-exists-4.0.0.tgz
path-is-absolute/-/path-is-absolute-1.0.1.tgz
path-key/-/path-key-3.1.1.tgz
path-parse/-/path-parse-1.0.7.tgz
path-platform/-/path-platform-0.11.15.tgz
pbkdf2/-/pbkdf2-3.1.2.tgz
performance-now/-/performance-now-2.1.0.tgz
picomatch/-/picomatch-2.3.0.tgz
platform/-/platform-1.3.6.tgz
prelude-ls/-/prelude-ls-1.2.1.tgz
process/-/process-0.11.10.tgz
process-nextick-args/-/process-nextick-args-2.0.1.tgz
progress/-/progress-2.0.3.tgz
psl/-/psl-1.8.0.tgz
public-encrypt/-/public-encrypt-4.0.3.tgz
bn.js/-/bn.js-4.12.0.tgz
punycode/-/punycode-1.4.1.tgz
qs/-/qs-6.5.2.tgz
querystring/-/querystring-0.2.0.tgz
querystring-es3/-/querystring-es3-0.2.1.tgz
randombytes/-/randombytes-2.1.0.tgz
randomfill/-/randomfill-1.0.4.tgz
read-only-stream/-/read-only-stream-2.0.0.tgz
readable-stream/-/readable-stream-2.3.7.tgz
safe-buffer/-/safe-buffer-5.1.2.tgz
string_decoder/-/string_decoder-1.1.1.tgz
readdirp/-/readdirp-3.6.0.tgz
regexp.prototype.flags/-/regexp.prototype.flags-1.3.1.tgz
regexpp/-/regexpp-3.2.0.tgz
request/-/request-2.88.2.tgz
require-directory/-/require-directory-2.1.1.tgz
require-from-string/-/require-from-string-2.0.2.tgz
resolve/-/resolve-1.20.0.tgz
resolve-from/-/resolve-from-4.0.0.tgz
resumer/-/resumer-0.0.0.tgz
rimraf/-/rimraf-3.0.2.tgz
ripemd160/-/ripemd160-2.0.2.tgz
safe-buffer/-/safe-buffer-5.2.1.tgz
safer-buffer/-/safer-buffer-2.1.2.tgz
semver/-/semver-7.3.5.tgz
sha.js/-/sha.js-2.4.11.tgz
shasum-object/-/shasum-object-1.0.0.tgz
shebang-command/-/shebang-command-2.0.0.tgz
shebang-regex/-/shebang-regex-3.0.0.tgz
shell-quote/-/shell-quote-1.7.2.tgz
side-channel/-/side-channel-1.0.4.tgz
signal-exit/-/signal-exit-3.0.5.tgz
simple-concat/-/simple-concat-1.0.1.tgz
slice-ansi/-/slice-ansi-4.0.0.tgz
source-map/-/source-map-0.5.7.tgz
sprintf-js/-/sprintf-js-1.0.3.tgz
sshpk/-/sshpk-1.16.1.tgz
stream-browserify/-/stream-browserify-3.0.0.tgz
readable-stream/-/readable-stream-3.6.0.tgz
stream-combiner2/-/stream-combiner2-1.1.1.tgz
stream-http/-/stream-http-3.2.0.tgz
readable-stream/-/readable-stream-3.6.0.tgz
stream-splicer/-/stream-splicer-2.0.1.tgz
string_decoder/-/string_decoder-1.3.0.tgz
string-width/-/string-width-4.2.3.tgz
string.prototype.trim/-/string.prototype.trim-1.2.4.tgz
string.prototype.trimend/-/string.prototype.trimend-1.0.4.tgz
string.prototype.trimstart/-/string.prototype.trimstart-1.0.4.tgz
strip-ansi/-/strip-ansi-6.0.1.tgz
strip-json-comments/-/strip-json-comments-3.1.1.tgz
subarg/-/subarg-1.0.0.tgz
supports-color/-/supports-color-7.2.0.tgz
syntax-error/-/syntax-error-1.4.0.tgz
table/-/table-6.7.2.tgz
ajv/-/ajv-8.6.3.tgz
json-schema-traverse/-/json-schema-traverse-1.0.0.tgz
tape/-/tape-5.3.1.tgz
resolve/-/resolve-2.0.0-next.3.tgz
test-exclude/-/test-exclude-6.0.0.tgz
text-table/-/text-table-0.2.0.tgz
through/-/through-2.3.8.tgz
through2/-/through2-2.0.5.tgz
timers-browserify/-/timers-browserify-1.4.2.tgz
to-regex-range/-/to-regex-range-5.0.1.tgz
tough-cookie/-/tough-cookie-2.5.0.tgz
punycode/-/punycode-2.1.1.tgz
tty-browserify/-/tty-browserify-0.0.1.tgz
tunnel-agent/-/tunnel-agent-0.6.0.tgz
tweetnacl/-/tweetnacl-0.14.5.tgz
type-check/-/type-check-0.4.0.tgz
type-fest/-/type-fest-0.20.2.tgz
typedarray/-/typedarray-0.0.6.tgz
uglify-js/-/uglify-js-3.14.2.tgz
umd/-/umd-3.0.3.tgz
unbox-primitive/-/unbox-primitive-1.0.1.tgz
undeclared-identifiers/-/undeclared-identifiers-1.1.3.tgz
uri-js/-/uri-js-4.4.1.tgz
punycode/-/punycode-2.1.1.tgz
url/-/url-0.11.0.tgz
punycode/-/punycode-1.3.2.tgz
util/-/util-0.12.4.tgz
util-deprecate/-/util-deprecate-1.0.2.tgz
uuid/-/uuid-3.4.0.tgz
v8-compile-cache/-/v8-compile-cache-2.3.0.tgz
v8-to-istanbul/-/v8-to-istanbul-8.1.0.tgz
convert-source-map/-/convert-source-map-1.8.0.tgz
safe-buffer/-/safe-buffer-5.1.2.tgz
source-map/-/source-map-0.7.3.tgz
verror/-/verror-1.10.0.tgz
core-util-is/-/core-util-is-1.0.2.tgz
vm-browserify/-/vm-browserify-1.1.2.tgz
watchify/-/watchify-4.0.0.tgz
readable-stream/-/readable-stream-3.6.0.tgz
through2/-/through2-4.0.2.tgz
which/-/which-2.0.2.tgz
which-boxed-primitive/-/which-boxed-primitive-1.0.2.tgz
which-collection/-/which-collection-1.0.1.tgz
which-typed-array/-/which-typed-array-1.1.7.tgz
word-wrap/-/word-wrap-1.2.3.tgz
wrap-ansi/-/wrap-ansi-7.0.0.tgz
wrappy/-/wrappy-1.0.2.tgz
xtend/-/xtend-4.0.2.tgz
y18n/-/y18n-5.0.8.tgz
yallist/-/yallist-4.0.0.tgz
yargs/-/yargs-16.2.0.tgz
yargs-parser/-/yargs-parser-20.2.9.tgz
yocto-queue/-/yocto-queue-0.1.0.tgz
)

DESCRIPTION="The fastest and smallest JavaScript polygon triangulation library for your WebGL apps"
HOMEPAGE="
	https://github.com/mapbox/earcut
	https://www.npmjs.com/package/earcut
"
SRC_URI="
	mirror://npm/${PN}/-/${P}.tgz
	https://raw.githubusercontent.com/Alessandro-Barbieri/guru-large-files/master/${CATEGORY}/${PN}/${P}-package-lock.json
	$(npm_packages_uris ${NPM_PACKAGES[@]})
"

LICENSE="ISC"
KEYWORDS="~amd64"

NPM_FLAGS="--save-dev"

src_prepare() {
	cp "${DISTDIR}/${P}-package-lock.json" package-lock.json || die
	node_src_prepare
}
