# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.2

EAPI=8

CRATES="
	aho-corasick@1.1.4
	alloca@0.4.0
	anes@0.1.6
	anstyle@1.0.14
	anyhow@1.0.103
	arrayvec@0.7.8
	autocfg@1.5.1
	bumpalo@3.20.3
	bytes@1.12.1
	cast@0.3.0
	cc@1.2.67
	cfg-if@1.0.4
	ciborium-io@0.2.2
	ciborium-ll@0.2.2
	ciborium@0.2.2
	clap@4.6.1
	clap_builder@4.6.0
	clap_lex@1.1.0
	criterion-plot@0.8.2
	criterion@0.8.2
	crossbeam-deque@0.8.7
	crossbeam-epoch@0.9.20
	crossbeam-utils@0.8.22
	crunchy@0.2.4
	daemonize@0.5.0
	either@1.16.0
	etherparse@0.13.0
	etherparse@0.18.2
	find-msvc-tools@0.1.9
	futures-core@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	half@2.7.1
	itertools@0.13.0
	itoa@1.0.18
	js-sys@0.3.103
	libc@0.2.186
	memchr@2.8.3
	nfq-updated@0.2.6
	num-traits@0.2.19
	once_cell@1.21.4
	oorandom@11.1.5
	page_size@0.6.0
	pin-project-lite@0.2.17
	plotters-backend@0.3.7
	plotters-svg@0.3.7
	plotters@0.3.7
	proc-macro2@1.0.106
	quote@1.0.46
	rayon-core@1.13.0
	rayon@1.12.0
	regex-automata@0.4.15
	regex-syntax@0.8.11
	regex@1.13.0
	rustversion@1.0.23
	same-file@1.0.6
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.150
	shlex@2.0.1
	slab@0.4.12
	socket2@0.6.5
	syn@2.0.118
	thiserror-impl@1.0.69
	thiserror-impl@2.0.18
	thiserror@1.0.69
	thiserror@2.0.18
	tinytemplate@1.2.1
	toml@0.5.11
	unicode-ident@1.0.24
	walkdir@2.5.0
	wasm-bindgen-macro-support@0.2.126
	wasm-bindgen-macro@0.2.126
	wasm-bindgen-shared@0.2.126
	wasm-bindgen@0.2.126
	web-sys@0.3.103
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.11
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windivert-sys@0.10.0
	windows-collections@0.3.2
	windows-core@0.62.2
	windows-future@0.3.2
	windows-implement@0.60.2
	windows-interface@0.59.3
	windows-link@0.2.1
	windows-numerics@0.3.1
	windows-result@0.4.1
	windows-services@0.26.1
	windows-strings@0.5.1
	windows-sys@0.61.2
	windows-targets@0.48.5
	windows-threading@0.2.1
	windows@0.48.0
	windows@0.62.2
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_msvc@0.48.5
	windows_i686_gnu@0.48.5
	windows_i686_msvc@0.48.5
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_msvc@0.48.5
	winres@0.1.12
	zerocopy-derive@0.8.54
	zerocopy@0.8.54
	zmij@1.0.23
"

RUST_MIN_VER="1.88"

inherit cargo

DESCRIPTION="System-wide DPI circumvention with minimal configuration"
HOMEPAGE="https://github.com/dilluti0n/dpibreak"
SRC_URI="
	https://github.com/dilluti0n/dpibreak/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="GPL-3+"
# Dependent crate licenses
LICENSE+=" Apache-2.0 LGPL-3+ MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"

RDEPEND="
	|| ( net-firewall/nftables net-firewall/iptables )
"

DEPEND="
	net-libs/libnetfilter_queue
	net-libs/libnfnetlink
"

QA_FLAGS_IGNORED="usr/bin/dpibreak"

src_install() {
	cargo_src_install
	doman dpibreak.1
	dodoc README.md CHANGELOG.md
}
