#!/sbin/openrc-run

export CONDUIT_CONFIG=${CONDUIT_CONFIG:-/etc/conduit/conduit.toml}

command="/usr/bin/conduit"
command_user="conduit:conduit"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"

output_log="/var/log/conduit.log"
error_log="/var/log/conduit.log"

depend() {
	need net
}

start_pre() {
	checkpath -d -m 0755 -o "$command_user" /var/lib/conduit
	checkpath -f -m 0644 -o "$command_user" "$output_log"
}
