diff --git a/Makefile b/Makefile
index d0c4dbe6..5cd8977a 100644
--- a/Makefile
+++ b/Makefile
@@ -12,7 +12,8 @@ WARN += -Wmissing-declarations
 #THEFT_INC=	-I${THEFT_PATH}/include/
 #LDFLAGS += -L${THEFT_PATH}/lib -ltheft
 
-CFLAGS += -std=c99 -g ${WARN} ${THEFT_INC} ${OPTIMIZE}
+MY_CFLAGS := -std=c99 ${WARN} ${THEFT_INC} ${OPTIMIZE} ${CFLAGS}
+CFLAGS := ${MY_CFLAGS}
 
 all: heatshrink test_runners libraries
 
@@ -66,8 +67,6 @@ RM ?=		rm
 
 install: libraries heatshrink
 	${INSTALL} -c heatshrink ${PREFIX}/bin/
-	${INSTALL} -c libheatshrink_static.a ${PREFIX}/lib/
-	${INSTALL} -c libheatshrink_dynamic.a ${PREFIX}/lib/
 	${INSTALL} -c heatshrink_common.h ${PREFIX}/include/
 	${INSTALL} -c heatshrink_config.h ${PREFIX}/include/
 	${INSTALL} -c heatshrink_encoder.h ${PREFIX}/include/
