# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	anyhow@1.0.42
	autocfg@1.0.1
	bitflags@1.2.1
	bitflags@2.4.1
	cfg-if@1.0.0
	clap@4.1.14
	clap_builder@4.1.14
	clap_derive@4.1.14
	clap_lex@0.4.1
	clipboard-win@5.4.0
	deranged@0.3.9
	endian-type@0.1.2
	errno@0.3.5
	error-code@3.2.0
	fd-lock@4.0.2
	heck@0.4.1
	hermit-abi@0.3.3
	home@0.5.5
	is-terminal@0.4.9
	itoa@1.0.9
	lazy_static@1.4.0
	libc@0.2.149
	linux-raw-sys@0.4.10
	log@0.4.14
	memchr@2.4.0
	memmap2@0.9.0
	memoffset@0.7.1
	nibble_vec@0.1.0
	nix@0.26.4
	nix@0.27.1
	num-conv@0.1.0
	num_threads@0.1.6
	once_cell@1.18.0
	pin-utils@0.1.0
	pom@3.2.0
	powerfmt@0.2.0
	proc-macro2@1.0.69
	quote@1.0.33
	radix_trie@0.2.1
	rustix@0.38.20
	rustyline-derive@0.10.0
	rustyline@13.0.0
	serde@1.0.189
	serde_derive@1.0.189
	simplelog@0.12.1
	smallvec@1.6.1
	strsim@0.10.0
	syn@2.0.38
	termcolor@1.1.2
	time-core@0.1.2
	time-macros@0.2.18
	time@0.3.36
	unicode-ident@1.0.12
	unicode-segmentation@1.8.0
	unicode-width@0.1.8
	utf8parse@0.2.0
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.48.0
	windows-sys@0.52.0
	windows-targets@0.48.5
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.48.5
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.48.5
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.48.5
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.48.5
	windows_x86_64_msvc@0.52.6
"

inherit cargo

DESCRIPTION="The btrfs debugger"
HOMEPAGE="https://github.com/danobi/btrd"
SRC_URI="https://github.com/danobi/btrd/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="GPL-2"
# Dependent crate licenses
LICENSE+=" Boost-1.0 MIT Unicode-DFS-2016"
SLOT="0"
KEYWORDS="~amd64"
