# Copyright 2017-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=8

CRATES="
	atty-0.2.14
	autocfg-1.1.0
	bitflags-1.3.2
	cfg-if-1.0.0
	clap-3.2.14
	clap_lex-0.2.4
	colored-2.0.0
	hashbrown-0.12.1
	hermit-abi-0.1.19
	indexmap-1.9.1
	itoa-1.0.2
	lazy_static-1.4.0
	libc-0.2.126
	log-0.4.17
	mpvipc-1.2.2
	os_str_bytes-6.1.0
	ryu-1.0.10
	serde-1.0.140
	serde_json-1.0.82
	strsim-0.10.0
	termcolor-1.1.3
	textwrap-0.15.0
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="mpc-like tool which connects to existing mpv instances through sockets."
HOMEPAGE="https://gitlab.com/mpv-ipc/mpvc"
SRC_URI="
$(cargo_crate_uris ${CRATES})
https://gitlab.com/mpv-ipc/${PN}/-/archive/v${PV}/${PN}-v${PV}.tar.gz -> ${P}.tar.gz
"
RESTRICT="mirror"
LICENSE="GPL-3+"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

S="${WORKDIR}/${PN}-v${PV}"
QA_FLAGS_IGNORED="usr/bin/mpvc"

DEPEND="media-video/mpv"
RDEPEND="${DEPEND}"
BDEPEND="dev-lang/rust"
