# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

CRATES="
	aho-corasick@1.1.4
	anstyle@1.0.13
	assert_cmd@2.1.1
	bstr@1.12.1
	cfg-if@1.0.4
	difflib@0.4.0
	env_filter@0.1.4
	env_logger@0.11.8
	evalexpr@12.0.3
	getrandom@0.2.16
	glob@0.3.3
	libc@0.2.177
	log@0.4.28
	memchr@2.7.6
	object@0.35.0
	predicates-core@1.0.9
	predicates-tree@1.0.12
	predicates@3.1.3
	proc-macro2@1.0.103
	quote@1.0.41
	regex-automata@0.4.13
	regex-syntax@0.8.8
	regex@1.12.2
	relative-path@1.9.3
	rstest@0.19.0
	rstest_macros@0.19.0
	rustc_version@0.4.1
	semver@1.0.27
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	syn@2.0.109
	termtree@0.5.1
	unicode-ident@1.0.22
	wait-timeout@0.2.1
	wasi@0.11.1+wasi-snapshot-preview1
"

inherit cargo

DESCRIPTION="Flips the memory layout of embedded programs to protect against stack overflows"
HOMEPAGE="https://github.com/knurling-rs/flip-link"
SRC_URI="
	${CARGO_CRATE_URIS}
	https://github.com/knurling-rs/flip-link/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+=" AGPL-3 MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"

RESTRICT="test" # requires non default target

QA_FLAGS_IGNORED="
	usr/bin/flip-link
"
