#!/sbin/openrc-run
# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

supervisor="supervise-daemon"
pidfile="/run/lms.pid"
command="/usr/bin/lms"
command_args=""
command_user="lms:lms"
start_stop_daemon_args="-d /var/lms \
                        -1 /var/log/lms/lms.log \
                        -2 /var/log/lms/lms.log"

depend() {
	need net
}
