# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

RUST_MIN_VER="1.93"
PYPI_VERIFY_REPO=https://github.com/facebook/pyrefly/

CRATES="
	addr2line@0.25.1
	adler2@2.0.1
	aho-corasick@1.1.4
	allocative@0.3.6
	allocative_derive@0.3.6
	allocator-api2@0.2.21
	anstream@0.6.21
	anstream@1.0.0
	anstyle-parse@0.2.7
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	anyhow@1.0.102
	append-only-vec@0.1.8
	arc-swap@1.9.1
	argfile@0.2.1
	arrayref@0.3.9
	arrayvec@0.7.6
	atomic@0.5.3
	attribute-derive-macro@0.10.5
	attribute-derive@0.10.5
	autocfg@1.5.1
	backtrace-on-stack-overflow@0.3.0
	base64@0.22.1
	bitflags@1.3.2
	bitflags@2.13.0
	blake3@1.8.2
	block-buffer@0.10.4
	bs58@0.5.1
	bstr@1.12.1
	bumpalo@3.20.3
	byteorder@1.5.0
	bytes@1.11.1
	capnp@0.25.5
	castaway@0.2.4
	cc@1.2.63
	cfg-if@1.0.4
	chacha20@0.10.0
	chrono@0.4.45
	clap@4.6.1
	clap_builder@4.6.0
	clap_derive@4.6.1
	clap_lex@1.1.0
	collection_literals@1.0.3
	colorchoice@1.0.5
	compact_str@0.9.1
	configparser@3.2.0
	console@0.16.1
	console_error_panic_hook@0.1.7
	constant_time_eq@0.3.1
	convert_case@0.11.0
	cpufeatures@0.2.17
	cpufeatures@0.3.0
	crossbeam-channel@0.5.15
	crossbeam-deque@0.8.6
	crossbeam-epoch@0.9.18
	crossbeam-utils@0.8.21
	crypto-common@0.1.7
	ctor@1.0.7
	darling@0.23.0
	darling_core@0.23.0
	darling_macro@0.23.0
	dashmap@6.2.1
	deranged@0.5.8
	derivative@2.2.0
	derive-where@1.6.1
	diff@0.1.13
	digest@0.10.7
	displaydoc@0.2.6
	dupe@0.9.1
	dupe_derive@0.9.1
	either@1.16.0
	embedded-io@0.7.1
	encode_unicode@1.0.0
	enum-iterator-derive@1.5.0
	enum-iterator@2.3.0
	equivalent@1.0.2
	errno@0.3.14
	faster-hex@0.6.1
	fastrand@2.4.1
	filetime@0.2.29
	find-msvc-tools@0.1.9
	foldhash@0.1.5
	foldhash@0.2.0
	form_urlencoded@1.2.2
	fs-err@2.11.0
	fsevent-sys@4.1.0
	futures-channel@0.3.32
	futures-core@0.3.32
	futures-executor@0.3.32
	futures-io@0.3.32
	futures-macro@0.3.32
	futures-sink@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	futures@0.1.31
	futures@0.3.32
	fuzzy-matcher@0.3.7
	fxhash@0.2.1
	generic-array@0.14.7
	get-size-derive2@0.9.0
	get-size2@0.9.0
	getopts@0.2.24
	getrandom@0.2.17
	getrandom@0.3.4
	getrandom@0.4.2
	gimli@0.32.3
	glob@0.3.3
	globset@0.4.18
	hashbrown@0.14.5
	hashbrown@0.15.5
	hashbrown@0.16.1
	hashbrown@0.17.1
	heck@0.5.0
	hex@0.4.3
	home@0.5.12
	human_bytes@0.4.3
	icu_collections@2.2.0
	icu_locale_core@2.2.0
	icu_normalizer@2.2.0
	icu_normalizer_data@2.2.0
	icu_properties@2.2.0
	icu_properties_data@2.2.0
	icu_provider@2.2.0
	id-arena@2.3.0
	ident_case@1.0.1
	idna@1.1.0
	idna_adapter@1.2.2
	ignore@0.4.26
	index_vec@0.1.4
	indexmap@2.14.0
	indicatif@0.18.4
	inotify-sys@0.1.5
	inotify@0.11.2
	interpolator@0.5.0
	is-macro@0.3.7
	is_terminal_polyfill@1.70.2
	itertools@0.14.0
	itoa@0.4.8
	itoa@1.0.18
	jobserver@0.1.34
	js-sys@0.3.100
	kqueue-sys@1.1.2
	kqueue@1.2.0
	lazy_static@1.5.0
	leb128fmt@0.1.0
	libc@0.2.186
	libmimalloc-sys@0.1.49
	link-section@0.18.2
	linktime-proc-macro@0.2.0
	linux-raw-sys@0.12.1
	linux-raw-sys@0.4.15
	litemap@0.8.2
	lock_api@0.4.14
	lock_free_hashtable@0.1.4
	log@0.4.32
	lsp-server@0.7.9
	manyhow-macros@0.11.4
	manyhow@0.11.4
	maplit@1.0.2
	matchers@0.2.0
	memchr@2.8.1
	memmap2@0.9.10
	memoffset@0.6.5
	memory-stats@1.2.0
	mimalloc@0.1.52
	miniz_oxide@0.8.8
	mio@1.2.1
	nix@0.23.1
	notify-types@2.1.0
	notify@8.2.0
	num-bigint@0.4.6
	num-conv@0.2.2
	num-integer@0.1.46
	num-traits@0.2.19
	object@0.37.3
	once_cell@1.21.4
	once_cell_polyfill@1.70.2
	ordermap@1.2.0
	os_str_bytes@7.1.1
	parking_lot@0.12.5
	parking_lot_core@0.9.12
	parse-display-derive@0.8.2
	parse-display@0.8.2
	paste@1.0.15
	path-absolutize@3.1.1
	path-dedot@3.1.1
	pathdiff@0.2.3
	percent-encoding@2.3.2
	phf@0.11.3
	phf_codegen@0.11.3
	phf_generator@0.11.3
	phf_shared@0.11.3
	pin-project-lite@0.2.17
	pkg-config@0.3.33
	portable-atomic@1.13.1
	potential_utf@0.1.5
	powerfmt@0.2.0
	ppv-lite86@0.2.21
	pretty_assertions@1.4.1
	prettyplease@0.2.37
	proc-macro-utils@0.10.0
	proc-macro2@1.0.106
	pulldown-cmark-escape@0.11.0
	pulldown-cmark@0.13.4
	quote-use-macros@0.8.4
	quote-use@0.8.4
	quote@1.0.45
	r-efi@5.3.0
	r-efi@6.0.0
	rand@0.10.1
	rand@0.8.6
	rand_chacha@0.3.1
	rand_core@0.10.1
	rand_core@0.6.4
	rayon-core@1.13.0
	rayon@1.12.0
	redox_syscall@0.5.18
	ref-cast-impl@1.0.25
	ref-cast@1.0.25
	regex-automata@0.4.14
	regex-syntax@0.7.5
	regex-syntax@0.8.10
	regex@1.12.3
	rustc-demangle@0.1.27
	rustc-hash@2.1.2
	rustix@0.38.44
	rustix@1.1.4
	ryu@0.2.8
	ryu@1.0.23
	same-file@1.0.6
	scopeguard@1.2.0
	seahash@4.1.0
	semver@1.0.28
	serde-wasm-bindgen@0.6.5
	serde@1.0.228
	serde_bser@0.4.0
	serde_bytes@0.11.19
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.150
	serde_jsonrc@0.1.0
	serde_repr@0.1.20
	serde_spanned@1.1.1
	serde_with@3.21.0
	serde_with_macros@3.21.0
	sha2@0.10.9
	sharded-slab@0.1.7
	shlex@2.0.1
	signal-hook-registry@1.4.8
	siphasher@1.0.3
	slab@0.4.12
	smallvec@1.15.1
	socket2@0.6.4
	stable_deref_trait@1.2.1
	starlark_map@0.14.2
	static_assertions@1.1.0
	static_interner@0.1.3
	strong_hash@0.1.0
	strong_hash_derive@0.1.0
	strsim@0.11.1
	structmeta-derive@0.2.0
	structmeta@0.2.0
	subtle@2.6.1
	syn@1.0.109
	syn@2.0.117
	synstructure@0.13.2
	tar@0.4.46
	tempfile@3.27.0
	terminal_size@0.4.4
	thin-vec@0.2.18
	thiserror-impl@1.0.69
	thiserror-impl@2.0.18
	thiserror@1.0.69
	thiserror@2.0.18
	thread_local@1.1.9
	tikv-jemalloc-sys@0.6.1+5.3.0-1-ge13ca993e8ccb9ba9847cc330696e02839f328f7
	tikv-jemallocator@0.6.1
	time-core@0.1.8
	time@0.3.47
	tinystr@0.8.3
	tinyvec@1.11.0
	tinyvec_macros@0.1.1
	tokio-macros@2.7.0
	tokio-util@0.6.10
	tokio@1.52.3
	toml@1.1.2+spec-1.1.0
	toml_datetime@1.1.1+spec-1.1.0
	toml_edit@0.25.12+spec-1.1.0
	toml_parser@1.1.2+spec-1.1.0
	toml_writer@1.1.1+spec-1.1.0
	tracing-attributes@0.1.31
	tracing-core@0.1.36
	tracing-subscriber@0.3.23
	tracing@0.1.44
	typenum@1.20.1
	unicase@2.9.0
	unicode-ident@1.0.24
	unicode-normalization@0.1.25
	unicode-segmentation@1.13.3
	unicode-width@0.2.2
	unicode-xid@0.2.6
	unicode_names2@1.3.0
	unicode_names2_generator@1.3.0
	unit-prefix@0.5.2
	url@2.5.8
	utf8_iter@1.0.4
	utf8parse@0.2.2
	uuid-rng-internal@1.23.3
	uuid@1.23.3
	valuable@0.1.1
	vec1@1.12.1
	version_check@0.9.5
	walkdir@2.5.0
	wasi@0.11.1+wasi-snapshot-preview1
	wasip2@1.0.3+wasi-0.2.9
	wasip3@0.4.0+wasi-0.3.0-rc-2026-01-06
	wasm-bindgen-macro-support@0.2.123
	wasm-bindgen-macro@0.2.123
	wasm-bindgen-shared@0.2.123
	wasm-bindgen@0.2.123
	wasm-encoder@0.244.0
	wasm-metadata@0.244.0
	wasmparser@0.244.0
	watchman_client@0.9.0
	web-time@1.1.0
	which@4.4.2
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.11
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-link@0.2.1
	windows-sys@0.52.0
	windows-sys@0.59.0
	windows-sys@0.60.2
	windows-sys@0.61.2
	windows-targets@0.52.6
	windows-targets@0.53.5
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_gnullvm@0.53.1
	windows_aarch64_msvc@0.52.6
	windows_aarch64_msvc@0.53.1
	windows_i686_gnu@0.52.6
	windows_i686_gnu@0.53.1
	windows_i686_gnullvm@0.52.6
	windows_i686_gnullvm@0.53.1
	windows_i686_msvc@0.52.6
	windows_i686_msvc@0.53.1
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnu@0.53.1
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_gnullvm@0.53.1
	windows_x86_64_msvc@0.52.6
	windows_x86_64_msvc@0.53.1
	winnow@1.0.1
	wit-bindgen-core@0.51.0
	wit-bindgen-rust-macro@0.51.0
	wit-bindgen-rust@0.51.0
	wit-bindgen@0.51.0
	wit-bindgen@0.57.1
	wit-component@0.244.0
	wit-parser@0.244.0
	writeable@0.6.3
	xattr@1.6.1
	xxhash-rust@0.8.15
	yansi@1.0.1
	yoke-derive@0.8.2
	yoke@0.8.3
	zerocopy-derive@0.8.50
	zerocopy@0.8.50
	zerofrom-derive@0.1.7
	zerofrom@0.1.8
	zerotrie@0.2.4
	zerovec-derive@0.11.3
	zerovec@0.11.6
	zmij@1.0.21
	zstd-safe@7.2.4
	zstd-sys@2.0.16+zstd.1.5.7
	zstd@0.13.3
"

declare -A GIT_CRATES=(
	[backtrace]='https://github.com/rust-lang/backtrace-rs;df979dcf80027eb047d7bb9e0874710c15009f31;backtrace-rs-%commit%'
	[lsp-types]='https://github.com/astral-sh/lsp-types;e15db0593f0ecbbd80599c3f5880e4bf5da1ca0c;lsp-types-%commit%'
	[ruff_annotate_snippets]='https://github.com/astral-sh/ruff;db5aa0a5f1b92cb91d910bf0866a967554dd94f5;ruff-%commit%/crates/ruff_annotate_snippets'
	[ruff_cache]='https://github.com/astral-sh/ruff;db5aa0a5f1b92cb91d910bf0866a967554dd94f5;ruff-%commit%/crates/ruff_cache'
	[ruff_diagnostics]='https://github.com/astral-sh/ruff;db5aa0a5f1b92cb91d910bf0866a967554dd94f5;ruff-%commit%/crates/ruff_diagnostics'
	[ruff_notebook]='https://github.com/astral-sh/ruff;db5aa0a5f1b92cb91d910bf0866a967554dd94f5;ruff-%commit%/crates/ruff_notebook'
	[ruff_python_ast]='https://github.com/astral-sh/ruff;db5aa0a5f1b92cb91d910bf0866a967554dd94f5;ruff-%commit%/crates/ruff_python_ast'
	[ruff_python_parser]='https://github.com/astral-sh/ruff;db5aa0a5f1b92cb91d910bf0866a967554dd94f5;ruff-%commit%/crates/ruff_python_parser'
	[ruff_python_trivia]='https://github.com/astral-sh/ruff;db5aa0a5f1b92cb91d910bf0866a967554dd94f5;ruff-%commit%/crates/ruff_python_trivia'
	[ruff_source_file]='https://github.com/astral-sh/ruff;db5aa0a5f1b92cb91d910bf0866a967554dd94f5;ruff-%commit%/crates/ruff_source_file'
	[ruff_text_size]='https://github.com/astral-sh/ruff;db5aa0a5f1b92cb91d910bf0866a967554dd94f5;ruff-%commit%/crates/ruff_text_size'
	[rustversion]='https://github.com/fbsource/rustversion;3f072e049635b7463275fc4edebbbed3840d9297;rustversion-%commit%'
)

inherit cargo pypi

DESCRIPTION="A fast type checker and language server for Python with powerful IDE features"
HOMEPAGE="
	https://pyrefly.org/
	https://github.com/facebook/pyrefly
	https://pypi.org/project/pyrefly/
"
SRC_URI+="
	${CARGO_CRATE_URIS}
"

S="${WORKDIR}/${P}/${PN}"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	0BSD Apache-2.0 BSD-2 BSD Boost-1.0 CC0-1.0 ISC MIT Unicode-3.0
	Unicode-DFS-2016 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

DEPEND="app-arch/zstd:="
RDEPEND="${DEPEND}"

src_unpack() {
	pypi_src_unpack
	cargo_src_unpack
}

src_prepare() {
	default

	local crate crate_patches crate_uri commit crate_dir host
	for crate in "${!GIT_CRATES[@]}"; do
		IFS=';' read -r crate_uri commit crate_dir host <<< "${GIT_CRATES[${crate}]}"
		: "${crate_dir:=${crate}-%commit%}"
		crate_patches+="${crate} = { path = \"${WORKDIR}/${crate_dir//%commit%/${commit}}\" };;"
	done
	printf -- "[patch.crates-io]\\n%s" "${crate_patches//;;/$'\n'}" \
		>> "${CARGO_HOME}/config.toml"
}

src_configure() {
	# zstd-sys https://wiki.gentoo.org/wiki/Project:Rust/sys_crates#zstd-sys
	export ZSTD_SYS_USE_PKG_CONFIG=1

	cargo_src_configure
}

src_test() {
	local -x CONFIG_DOC_PATH="${WORKDIR}/${P}/website/docs/configuration.mdx"
	local -x ERROR_KINDS_DOC_PATH="${WORKDIR}/${P}/website/docs/error-kinds.mdx"

	local -x TEST_FILES_PATH="${S}/lib/test/lsp/lsp_interaction/test_files"

	local -x PYDANTIC_TEST_PATH="${S}/lib/test/pydantic/third-party"
	local -x DJANGO_TEST_PATH="${S}/lib/test/django/third-party"
	local -x FACTORY_BOY_TEST_PATH="${S}/lib/test/factory_boy/third-party"
	local -x ATTRS_TEST_PATH="${S}/lib/test/attrs/third-party"
	local -x MARSHMALLOW_TEST_PATH="${S}/lib/test/marshmallow/third-party"

	local -x GLEAN_SNAPSHOTS_PATH="${S}/lib/report/glean/snapshots"
	local -x REPORT_TEST_PATH="${S}/lib/test/report/test_files"
	local -x STUBGEN_TEST_PATH="${S}/lib/test/stubgen"

	cargo_src_test --no-fail-fast
}
