# Copyright 2024-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.3

EAPI=8

CARGO_OPTIONAL=1
DISTUTILS_USE_PEP517=setuptools
DISTUTILS_EXT=1
PYTHON_COMPAT=( python3_{12..14} pypy3_11 )
RUST_MIN_VER="1.87.0"

CRATES="
	aes@0.8.4
	anyhow@1.0.102
	autocfg@1.5.0
	bitflags@2.11.0
	block-buffer@0.10.4
	cfg-if@1.0.4
	cipher@0.4.4
	cpufeatures@0.2.17
	crypto-common@0.1.7
	digest@0.10.7
	equivalent@1.0.2
	foldhash@0.1.5
	generic-array@0.14.7
	getrandom@0.2.17
	getrandom@0.4.2
	glass_pumpkin@1.10.0
	grammers-crypto@0.7.0
	hashbrown@0.15.5
	hashbrown@0.17.0
	heck@0.5.0
	hmac@0.12.1
	id-arena@2.3.0
	indexmap@2.14.0
	inout@0.1.4
	itoa@1.0.18
	leb128fmt@0.1.0
	libc@0.2.184
	log@0.4.29
	memchr@2.8.0
	num-bigint@0.4.6
	num-integer@0.1.46
	num-traits@0.2.19
	once_cell@1.21.4
	pbkdf2@0.12.2
	portable-atomic@1.13.1
	prettyplease@0.2.37
	proc-macro2@1.0.106
	pyo3-build-config@0.28.3
	pyo3-ffi@0.28.3
	pyo3-macros-backend@0.28.3
	pyo3-macros@0.28.3
	pyo3@0.28.3
	quote@1.0.45
	r-efi@6.0.0
	rand_core@0.10.0
	semver@1.0.28
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.149
	sha1@0.10.6
	sha2@0.10.9
	subtle@2.6.1
	syn@2.0.117
	target-lexicon@0.13.5
	typenum@1.19.0
	unicode-ident@1.0.24
	unicode-xid@0.2.6
	version_check@0.9.5
	wasi@0.11.1+wasi-snapshot-preview1
	wasip2@1.0.2+wasi-0.2.9
	wasip3@0.4.0+wasi-0.3.0-rc-2026-01-06
	wasm-encoder@0.244.0
	wasm-metadata@0.244.0
	wasmparser@0.244.0
	wit-bindgen-core@0.51.0
	wit-bindgen-rust-macro@0.51.0
	wit-bindgen-rust@0.51.0
	wit-bindgen@0.51.0
	wit-component@0.244.0
	wit-parser@0.244.0
	zmij@1.0.21
"

inherit cargo distutils-r1 pypi

DESCRIPTION="Cryptographic utilities for Telegram"
HOMEPAGE="
	https://pypi.org/project/cryptg/
	https://github.com/cher-nov/cryptg/
"
SRC_URI+=" ${CARGO_CRATE_URIS}"

LICENSE="CC0-1.0"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD MIT Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

BDEPEND="
	${RUST_DEPEND}
	dev-python/setuptools-rust[${PYTHON_USEDEP}]
"

# rust does not use *FLAGS from make.conf, silence portage warning
QA_FLAGS_IGNORED=".*"

EPYTEST_PLUGINS=( pytest-import-check )

distutils_enable_tests import-check

src_unpack() {
	cargo_src_unpack
}
