# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

NPM_BUNDLE=1

inherit node

NPM_PACKAGES=(
acorn/-/acorn-7.4.1.tgz
acorn-jsx/-/acorn-jsx-5.3.1.tgz
add-stream/-/add-stream-1.0.0.tgz
ajv/-/ajv-6.12.6.tgz
ansi-colors/-/ansi-colors-3.2.3.tgz
ansi-colors/-/ansi-colors-4.1.1.tgz
ansi-regex/-/ansi-regex-3.0.0.tgz
ansi-regex/-/ansi-regex-4.1.0.tgz
ansi-regex/-/ansi-regex-5.0.0.tgz
ansi-styles/-/ansi-styles-3.2.1.tgz
ansi-styles/-/ansi-styles-4.3.0.tgz
anymatch/-/anymatch-3.1.1.tgz
argparse/-/argparse-1.0.10.tgz
array-find-index/-/array-find-index-1.0.2.tgz
array-ify/-/array-ify-1.0.0.tgz
arrify/-/arrify-1.0.1.tgz
astral-regex/-/astral-regex-1.0.0.tgz
@babel/code-frame/-/code-frame-7.12.11.tgz
@babel/helper-validator-identifier/-/helper-validator-identifier-7.12.11.tgz
@babel/highlight/-/highlight-7.10.4.tgz
balanced-match/-/balanced-match-1.0.0.tgz
benchmark/-/benchmark-2.1.4.tgz
binary-extensions/-/binary-extensions-2.2.0.tgz
brace-expansion/-/brace-expansion-1.1.11.tgz
braces/-/braces-3.0.2.tgz
browser-stdout/-/browser-stdout-1.3.1.tgz
buffer-from/-/buffer-from-1.1.1.tgz
call-bind/-/call-bind-1.0.2.tgz
callsites/-/callsites-3.1.0.tgz
camelcase/-/camelcase-2.1.1.tgz
camelcase/-/camelcase-4.1.0.tgz
camelcase/-/camelcase-5.3.1.tgz
camelcase-keys/-/camelcase-keys-2.1.0.tgz
camelcase-keys/-/camelcase-keys-4.2.0.tgz
camelcase-keys/-/camelcase-keys-6.2.2.tgz
chalk/-/chalk-2.4.2.tgz
chalk/-/chalk-4.1.0.tgz
chokidar/-/chokidar-3.3.0.tgz
cliui/-/cliui-5.0.0.tgz
cliui/-/cliui-6.0.0.tgz
color-convert/-/color-convert-1.9.3.tgz
color-convert/-/color-convert-2.0.1.tgz
color-name/-/color-name-1.1.3.tgz
color-name/-/color-name-1.1.4.tgz
compare-func/-/compare-func-2.0.0.tgz
concat-map/-/concat-map-0.0.1.tgz
concat-stream/-/concat-stream-2.0.0.tgz
conventional-changelog-angular/-/conventional-changelog-angular-5.0.12.tgz
conventional-changelog-atom/-/conventional-changelog-atom-2.0.8.tgz
conventional-changelog-codemirror/-/conventional-changelog-codemirror-2.0.8.tgz
conventional-changelog-config-spec/-/conventional-changelog-config-spec-2.1.0.tgz
conventional-changelog/-/conventional-changelog-3.1.23.tgz
conventional-changelog-conventionalcommits/-/conventional-changelog-conventionalcommits-4.4.0.tgz
conventional-changelog-core/-/conventional-changelog-core-4.2.1.tgz
conventional-changelog-ember/-/conventional-changelog-ember-2.0.9.tgz
conventional-changelog-eslint/-/conventional-changelog-eslint-3.0.9.tgz
conventional-changelog-express/-/conventional-changelog-express-2.0.6.tgz
conventional-changelog-jquery/-/conventional-changelog-jquery-3.0.11.tgz
conventional-changelog-jshint/-/conventional-changelog-jshint-2.0.9.tgz
conventional-changelog-preset-loader/-/conventional-changelog-preset-loader-2.3.4.tgz
conventional-changelog-writer/-/conventional-changelog-writer-4.0.18.tgz
conventional-commits-filter/-/conventional-commits-filter-2.0.7.tgz
conventional-commits-parser/-/conventional-commits-parser-3.2.0.tgz
conventional-recommended-bump/-/conventional-recommended-bump-6.0.10.tgz
core-util-is/-/core-util-is-1.0.2.tgz
cross-spawn/-/cross-spawn-7.0.3.tgz
currently-unhandled/-/currently-unhandled-0.4.1.tgz
dargs/-/dargs-4.1.0.tgz
dateformat/-/dateformat-3.0.3.tgz
debug/-/debug-3.2.6.tgz
debug/-/debug-4.3.1.tgz
decamelize/-/decamelize-1.2.0.tgz
decamelize-keys/-/decamelize-keys-1.1.0.tgz
deep-is/-/deep-is-0.1.3.tgz
define-properties/-/define-properties-1.1.3.tgz
detect-indent/-/detect-indent-6.0.0.tgz
detect-newline/-/detect-newline-3.1.0.tgz
diff/-/diff-3.5.0.tgz
doctrine/-/doctrine-3.0.0.tgz
dotgitignore/-/dotgitignore-2.1.0.tgz
dot-prop/-/dot-prop-5.3.0.tgz
emoji-regex/-/emoji-regex-7.0.3.tgz
emoji-regex/-/emoji-regex-8.0.0.tgz
enquirer/-/enquirer-2.3.6.tgz
error-ex/-/error-ex-1.3.2.tgz
es-abstract/-/es-abstract-1.18.0-next.1.tgz
escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
eslint/-/eslint-7.15.0.tgz
@eslint/eslintrc/-/eslintrc-0.2.2.tgz
eslint-scope/-/eslint-scope-5.1.1.tgz
eslint-utils/-/eslint-utils-2.1.0.tgz
eslint-visitor-keys/-/eslint-visitor-keys-1.3.0.tgz
eslint-visitor-keys/-/eslint-visitor-keys-2.0.0.tgz
espree/-/espree-7.3.1.tgz
esprima/-/esprima-4.0.1.tgz
esquery/-/esquery-1.3.1.tgz
esrecurse/-/esrecurse-4.3.0.tgz
es-to-primitive/-/es-to-primitive-1.2.1.tgz
estraverse/-/estraverse-4.3.0.tgz
estraverse/-/estraverse-5.2.0.tgz
esutils/-/esutils-2.0.3.tgz
fast-deep-equal/-/fast-deep-equal-3.1.3.tgz
fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz
fast-levenshtein/-/fast-levenshtein-2.0.6.tgz
figures/-/figures-3.2.0.tgz
file-entry-cache/-/file-entry-cache-6.0.0.tgz
fill-range/-/fill-range-7.0.1.tgz
find-up/-/find-up-1.1.2.tgz
find-up/-/find-up-2.1.0.tgz
find-up/-/find-up-3.0.0.tgz
find-up/-/find-up-4.1.0.tgz
flat-cache/-/flat-cache-3.0.4.tgz
flat/-/flat-4.1.1.tgz
flatted/-/flatted-3.1.0.tgz
fs-access/-/fs-access-1.0.1.tgz
fsevents/-/fsevents-2.1.3.tgz
fs.realpath/-/fs.realpath-1.0.0.tgz
functional-red-black-tree/-/functional-red-black-tree-1.0.1.tgz
function-bind/-/function-bind-1.1.1.tgz
get-caller-file/-/get-caller-file-2.0.5.tgz
get-intrinsic/-/get-intrinsic-1.0.2.tgz
get-pkg-repo/-/get-pkg-repo-1.4.0.tgz
get-stdin/-/get-stdin-4.0.1.tgz
gitconfiglocal/-/gitconfiglocal-1.0.0.tgz
git-raw-commits/-/git-raw-commits-2.0.0.tgz
git-remote-origin-url/-/git-remote-origin-url-2.0.0.tgz
git-semver-tags/-/git-semver-tags-4.1.1.tgz
globals/-/globals-12.4.0.tgz
glob/-/glob-7.1.3.tgz
glob/-/glob-7.1.6.tgz
glob-parent/-/glob-parent-5.1.1.tgz
graceful-fs/-/graceful-fs-4.2.4.tgz
growl/-/growl-1.10.5.tgz
handlebars/-/handlebars-4.7.6.tgz
hard-rejection/-/hard-rejection-2.1.0.tgz
has-flag/-/has-flag-3.0.0.tgz
has-flag/-/has-flag-4.0.0.tgz
has/-/has-1.0.3.tgz
has-symbols/-/has-symbols-1.0.1.tgz
he/-/he-1.2.0.tgz
hosted-git-info/-/hosted-git-info-2.8.8.tgz
hosted-git-info/-/hosted-git-info-3.0.7.tgz
ignore/-/ignore-4.0.6.tgz
import-fresh/-/import-fresh-3.2.2.tgz
imurmurhash/-/imurmurhash-0.1.4.tgz
indent-string/-/indent-string-2.1.0.tgz
indent-string/-/indent-string-3.2.0.tgz
indent-string/-/indent-string-4.0.0.tgz
inflight/-/inflight-1.0.6.tgz
inherits/-/inherits-2.0.4.tgz
ini/-/ini-1.3.8.tgz
interpret/-/interpret-1.4.0.tgz
isarray/-/isarray-1.0.0.tgz
is-arrayish/-/is-arrayish-0.2.1.tgz
is-binary-path/-/is-binary-path-2.1.0.tgz
is-buffer/-/is-buffer-2.0.5.tgz
is-callable/-/is-callable-1.2.2.tgz
is-core-module/-/is-core-module-2.2.0.tgz
is-date-object/-/is-date-object-1.0.2.tgz
isexe/-/isexe-2.0.0.tgz
is-extglob/-/is-extglob-2.1.1.tgz
is-finite/-/is-finite-1.1.0.tgz
is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz
is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz
is-glob/-/is-glob-4.0.1.tgz
is-negative-zero/-/is-negative-zero-2.0.1.tgz
is-number/-/is-number-7.0.0.tgz
is-obj/-/is-obj-2.0.0.tgz
is-plain-obj/-/is-plain-obj-1.1.0.tgz
is-regex/-/is-regex-1.1.1.tgz
is-symbol/-/is-symbol-1.0.3.tgz
is-text-path/-/is-text-path-1.0.1.tgz
is-utf8/-/is-utf8-0.2.1.tgz
json-parse-better-errors/-/json-parse-better-errors-1.0.2.tgz
json-parse-even-better-errors/-/json-parse-even-better-errors-2.3.1.tgz
jsonparse/-/jsonparse-1.3.1.tgz
json-schema-traverse/-/json-schema-traverse-0.4.1.tgz
json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz
JSONStream/-/JSONStream-1.3.5.tgz
json-stringify-safe/-/json-stringify-safe-5.0.1.tgz
js-tokens/-/js-tokens-4.0.0.tgz
js-yaml/-/js-yaml-3.13.1.tgz
js-yaml/-/js-yaml-3.14.1.tgz
kind-of/-/kind-of-6.0.3.tgz
levn/-/levn-0.4.1.tgz
lines-and-columns/-/lines-and-columns-1.1.6.tgz
load-json-file/-/load-json-file-1.1.0.tgz
load-json-file/-/load-json-file-4.0.0.tgz
locate-path/-/locate-path-2.0.0.tgz
locate-path/-/locate-path-3.0.0.tgz
locate-path/-/locate-path-5.0.0.tgz
lodash.ismatch/-/lodash.ismatch-4.4.0.tgz
lodash/-/lodash-4.17.15.tgz
lodash/-/lodash-4.17.20.tgz
lodash._reinterpolate/-/lodash._reinterpolate-3.0.0.tgz
lodash.template/-/lodash.template-4.5.0.tgz
lodash.templatesettings/-/lodash.templatesettings-4.2.0.tgz
log-symbols/-/log-symbols-3.0.0.tgz
loud-rejection/-/loud-rejection-1.6.0.tgz
lru-cache/-/lru-cache-6.0.0.tgz
map-obj/-/map-obj-1.0.1.tgz
map-obj/-/map-obj-2.0.0.tgz
map-obj/-/map-obj-4.1.0.tgz
meow/-/meow-3.7.0.tgz
meow/-/meow-4.0.1.tgz
meow/-/meow-7.1.1.tgz
meow/-/meow-8.0.0.tgz
mime-db/-/mime-db-1.44.0.tgz
mime-db/-/mime-db-1.45.0.tgz
mime-score/-/mime-score-1.2.0.tgz
mime-types/-/mime-types-2.1.27.tgz
minimatch/-/minimatch-3.0.4.tgz
minimist/-/minimist-1.2.0.tgz
minimist/-/minimist-1.2.5.tgz
minimist-options/-/minimist-options-3.0.2.tgz
minimist-options/-/minimist-options-4.1.0.tgz
min-indent/-/min-indent-1.0.1.tgz
mkdirp/-/mkdirp-0.5.5.tgz
mocha/-/mocha-7.2.0.tgz
modify-values/-/modify-values-1.0.1.tgz
ms/-/ms-2.1.1.tgz
ms/-/ms-2.1.2.tgz
natural-compare/-/natural-compare-1.4.0.tgz
neo-async/-/neo-async-2.6.2.tgz
node-environment-flags/-/node-environment-flags-1.0.6.tgz
normalize-package-data/-/normalize-package-data-2.5.0.tgz
normalize-package-data/-/normalize-package-data-3.0.0.tgz
normalize-path/-/normalize-path-3.0.0.tgz
null-check/-/null-check-1.0.0.tgz
number-is-nan/-/number-is-nan-1.0.1.tgz
object.assign/-/object.assign-4.1.0.tgz
object-assign/-/object-assign-4.1.1.tgz
object.assign/-/object.assign-4.1.2.tgz
object.getownpropertydescriptors/-/object.getownpropertydescriptors-2.1.1.tgz
object-inspect/-/object-inspect-1.9.0.tgz
object-keys/-/object-keys-1.1.1.tgz
once/-/once-1.4.0.tgz
optionator/-/optionator-0.9.1.tgz
parent-module/-/parent-module-1.0.1.tgz
parse-github-repo-url/-/parse-github-repo-url-1.4.1.tgz
parse-json/-/parse-json-2.2.0.tgz
parse-json/-/parse-json-4.0.0.tgz
parse-json/-/parse-json-5.1.0.tgz
path-exists/-/path-exists-2.1.0.tgz
path-exists/-/path-exists-3.0.0.tgz
path-exists/-/path-exists-4.0.0.tgz
path-is-absolute/-/path-is-absolute-1.0.1.tgz
path-key/-/path-key-3.1.1.tgz
path-parse/-/path-parse-1.0.6.tgz
path-type/-/path-type-1.1.0.tgz
path-type/-/path-type-3.0.0.tgz
picomatch/-/picomatch-2.2.2.tgz
pify/-/pify-2.3.0.tgz
pify/-/pify-3.0.0.tgz
pinkie/-/pinkie-2.0.4.tgz
pinkie-promise/-/pinkie-promise-2.0.1.tgz
platform/-/platform-1.3.5.tgz
p-limit/-/p-limit-1.3.0.tgz
p-limit/-/p-limit-2.3.0.tgz
p-locate/-/p-locate-2.0.0.tgz
p-locate/-/p-locate-3.0.0.tgz
p-locate/-/p-locate-4.1.0.tgz
prelude-ls/-/prelude-ls-1.2.1.tgz
process-nextick-args/-/process-nextick-args-2.0.1.tgz
progress/-/progress-2.0.3.tgz
p-try/-/p-try-1.0.0.tgz
p-try/-/p-try-2.2.0.tgz
punycode/-/punycode-2.1.1.tgz
q/-/q-1.5.1.tgz
quick-lru/-/quick-lru-1.1.0.tgz
quick-lru/-/quick-lru-4.0.1.tgz
readable-stream/-/readable-stream-2.3.7.tgz
readable-stream/-/readable-stream-3.6.0.tgz
readdirp/-/readdirp-3.2.0.tgz
read-pkg/-/read-pkg-1.1.0.tgz
read-pkg/-/read-pkg-3.0.0.tgz
read-pkg/-/read-pkg-5.2.0.tgz
read-pkg-up/-/read-pkg-up-1.0.1.tgz
read-pkg-up/-/read-pkg-up-3.0.0.tgz
read-pkg-up/-/read-pkg-up-7.0.1.tgz
rechoir/-/rechoir-0.6.2.tgz
redent/-/redent-1.0.0.tgz
redent/-/redent-2.0.0.tgz
redent/-/redent-3.0.0.tgz
regexpp/-/regexpp-3.1.0.tgz
repeating/-/repeating-2.0.1.tgz
require-directory/-/require-directory-2.1.1.tgz
require-like/-/require-like-0.1.2.tgz
require-main-filename/-/require-main-filename-2.0.0.tgz
resolve-from/-/resolve-from-4.0.0.tgz
resolve/-/resolve-1.19.0.tgz
rimraf/-/rimraf-3.0.2.tgz
runmd/-/runmd-1.3.2.tgz
safe-buffer/-/safe-buffer-5.1.2.tgz
safe-buffer/-/safe-buffer-5.2.1.tgz
semver/-/semver-5.7.1.tgz
semver/-/semver-6.3.0.tgz
semver/-/semver-7.3.4.tgz
set-blocking/-/set-blocking-2.0.0.tgz
shebang-command/-/shebang-command-2.0.0.tgz
shebang-regex/-/shebang-regex-3.0.0.tgz
shelljs/-/shelljs-0.8.4.tgz
signal-exit/-/signal-exit-3.0.3.tgz
slice-ansi/-/slice-ansi-2.1.0.tgz
source-map/-/source-map-0.6.1.tgz
spdx-correct/-/spdx-correct-3.1.1.tgz
spdx-exceptions/-/spdx-exceptions-2.3.0.tgz
spdx-expression-parse/-/spdx-expression-parse-3.0.1.tgz
spdx-license-ids/-/spdx-license-ids-3.0.7.tgz
split2/-/split2-2.2.0.tgz
split/-/split-1.0.1.tgz
sprintf-js/-/sprintf-js-1.0.3.tgz
standard-version/-/standard-version-9.0.0.tgz
string_decoder/-/string_decoder-1.1.1.tgz
string_decoder/-/string_decoder-1.3.0.tgz
stringify-package/-/stringify-package-1.0.1.tgz
string.prototype.trimend/-/string.prototype.trimend-1.0.3.tgz
string.prototype.trimstart/-/string.prototype.trimstart-1.0.3.tgz
string-width/-/string-width-2.1.1.tgz
string-width/-/string-width-3.1.0.tgz
string-width/-/string-width-4.2.0.tgz
strip-ansi/-/strip-ansi-4.0.0.tgz
strip-ansi/-/strip-ansi-5.2.0.tgz
strip-ansi/-/strip-ansi-6.0.0.tgz
strip-bom/-/strip-bom-2.0.0.tgz
strip-bom/-/strip-bom-3.0.0.tgz
strip-indent/-/strip-indent-1.0.1.tgz
strip-indent/-/strip-indent-2.0.0.tgz
strip-indent/-/strip-indent-3.0.0.tgz
strip-json-comments/-/strip-json-comments-2.0.1.tgz
strip-json-comments/-/strip-json-comments-3.1.1.tgz
supports-color/-/supports-color-5.5.0.tgz
supports-color/-/supports-color-6.0.0.tgz
supports-color/-/supports-color-7.2.0.tgz
table/-/table-5.4.6.tgz
text-extensions/-/text-extensions-1.9.0.tgz
text-table/-/text-table-0.2.0.tgz
through2/-/through2-2.0.5.tgz
through2/-/through2-4.0.2.tgz
through/-/through-2.3.8.tgz
to-regex-range/-/to-regex-range-5.0.1.tgz
trim-newlines/-/trim-newlines-1.0.0.tgz
trim-newlines/-/trim-newlines-2.0.0.tgz
trim-newlines/-/trim-newlines-3.0.0.tgz
trim-off-newlines/-/trim-off-newlines-1.0.1.tgz
type-check/-/type-check-0.4.0.tgz
typedarray/-/typedarray-0.0.6.tgz
type-fest/-/type-fest-0.13.1.tgz
type-fest/-/type-fest-0.18.1.tgz
type-fest/-/type-fest-0.6.0.tgz
type-fest/-/type-fest-0.8.1.tgz
@types/minimist/-/minimist-1.2.1.tgz
@types/normalize-package-data/-/normalize-package-data-2.4.0.tgz
uglify-js/-/uglify-js-3.12.1.tgz
uri-js/-/uri-js-4.4.0.tgz
util-deprecate/-/util-deprecate-1.0.2.tgz
v8-compile-cache/-/v8-compile-cache-2.2.0.tgz
validate-npm-package-license/-/validate-npm-package-license-3.0.4.tgz
which-module/-/which-module-2.0.0.tgz
which/-/which-1.3.1.tgz
which/-/which-2.0.2.tgz
wide-align/-/wide-align-1.1.3.tgz
wordwrap/-/wordwrap-1.0.0.tgz
word-wrap/-/word-wrap-1.2.3.tgz
wrap-ansi/-/wrap-ansi-5.1.0.tgz
wrap-ansi/-/wrap-ansi-6.2.0.tgz
wrappy/-/wrappy-1.0.2.tgz
xtend/-/xtend-4.0.2.tgz
y18n/-/y18n-4.0.1.tgz
yallist/-/yallist-4.0.0.tgz
yargs-parser/-/yargs-parser-13.1.2.tgz
yargs-parser/-/yargs-parser-18.1.3.tgz
yargs-parser/-/yargs-parser-20.2.4.tgz
yargs-unparser/-/yargs-unparser-1.6.0.tgz
yargs/-/yargs-13.3.2.tgz
yargs/-/yargs-15.4.1.tgz
)

DESCRIPTION="A comprehensive library for mime-type mapping"
HOMEPAGE="
	https://github.com/broofa/mime
	https://www.npmjs.com/package/mime
"
SRC_URI="
	https://github.com/broofa/mime/archive/refs/tags/v${PV}.tar.gz -> ${P}.tgz
	https://raw.githubusercontent.com/Alessandro-Barbieri/guru-large-files/master/${CATEGORY}/${PN}/${P}-package-lock.json
	$(npm_packages_uris ${NPM_PACKAGES[@]})
"
S="${WORKDIR}/${P}"

LICENSE="MIT"
KEYWORDS="~amd64"

NPM_FLAGS="--save-dev"

src_prepare() {
	cp "${DISTDIR}/${P}-package-lock.json" package-lock.json || die
	node_src_prepare
}
