--- a/makefile.in	2021-04-11 20:54:38.081969329 +0200
+++ b/makefile.in	2021-04-11 21:42:48.789853703 +0200
@@ -18,8 +18,7 @@
 LIBS = @LIBS@
 RANLIB = @RANLIB@
 
-
-CFLAGS = -O3 -fPIC
+CFLAGS += -fPIC
 
 
 .c.o:
@@ -80,45 +79,45 @@
 
 $(LIST1): $(HBASE)
 part1: $(LIST1)
-	ar ru libmeschach.a $(LIST1)
+	$(AR) ru libmeschach.a $(LIST1)
 	$(RANLIB) libmeschach.a
 #	$(CC) -shared -o libmeschach.so $(LIST1)
 
 $(LIST2): $(HBASE) matrix2.h
 part2: $(LIST2)
-	ar ru libmeschach.a $(LIST2)
+	$(AR) ru libmeschach.a $(LIST2)
 	$(RANLIB) libmeschach.a
 #	$(CC) -shared -o libmeschach.so $(LIST2)
 
 $(LIST3): $(HBASE) sparse.h sparse2.h
 part3: $(LIST3)
-	ar ru libmeschach.a $(LIST3)
+	$(AR) ru libmeschach.a $(LIST3)
 	$(RANLIB) libmeschach.a
 #	$(CC) -shared -o libmeschach.so $(LIST3)
 
 $(ZLIST1): $(HBASDE) zmatrix.h
 zpart1: $(ZLIST1)
-	ar ru libmeschach.a $(ZLIST1)
+	$(AR) ru libmeschach.a $(ZLIST1)
 	$(RANLIB) libmeschach.a
 #	$(CC) -shared -o libmeschach.so $(ZLIST1)
 
 $(ZLIST2): $(HBASE) zmatrix.h zmatrix2.h 
 zpart2: $(ZLIST2)
-	ar ru libmeschach.a $(ZLIST2)
+	$(AR) ru libmeschach.a $(ZLIST2)
 	$(RANLIB) libmeschach.a
 #	$(CC) -shared -o libmeschach.so $(ZLIST2)
 
 $(OLDLIST): $(HBASE) sparse.h sparse2.h 
 oldpart: $(OLDLIST)
-	ar ru libmeschach.a $(OLDLIST)
+	$(AR) ru libmeschach.a $(OLDLIST)
 	$(RANLIB) libmeschach.a
 #	$(CC) -shared -o libmeschach.so $(OLDLIST)
 
 shared:   $(ALL_LISTS)
-	$(CC) -shared -o libmeschach.so $(ALL_LISTS) -lc -lm -Wl,-soname -Wl,libmeschach.so.$(vers)
+	$(CC) $(LDFLAGS) -shared -o libmeschach.so $(ALL_LISTS) -lc -lm -Wl,-soname -Wl,libmeschach.so.$(vers)
 
 static:  $(ALL_LISTS)
-	ar ru libmeschach.a $(ALL_LISTS)
+	$(AR) ru libmeschach.a $(ALL_LISTS)
 	$(RANLIB) libmeschach.a
 
 
@@ -200,31 +199,31 @@
 alltorture: torture sptort ztorture memtort itertort mfuntort iotort
 
 torture:torture.o libmeschach.a
-	$(CC) $(CFLAGS) $(DEFS) -o torture torture.o \
-	libmeschach.a $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(DEFS) -fPIE -o torture torture.o \
+	-lmeschach -L. $(LIBS)
 sptort:sptort.o libmeschach.a
-	$(CC) $(CFLAGS) $(DEFS) -o sptort sptort.o \
-	libmeschach.a $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(DEFS) -fPIE -o sptort sptort.o \
+	-lmeschach -L. $(LIBS)
 memtort: memtort.o libmeschach.a
-	$(CC) $(CFLAGS) $(DEFS) -o memtort memtort.o \
-	libmeschach.a $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(DEFS) -fPIE -o memtort memtort.o \
+	-lmeschach -L. $(LIBS)
 ztorture:ztorture.o libmeschach.a
-	$(CC) $(CFLAGS) $(DEFS) -o ztorture ztorture.o \
-	libmeschach.a $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(DEFS) -fPIE -o ztorture ztorture.o \
+	-lmeschach -L. $(LIBS)
 itertort: itertort.o libmeschach.a
-	$(CC) $(CFLAGS) $(DEFS) -o itertort itertort.o \
-	libmeschach.a $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(DEFS) -fPIE -o itertort itertort.o \
+	-lmeschach -L. $(LIBS)
 
 iotort: iotort.o libmeschach.a
-	$(CC) $(CFLAGS) $(DEFS) -o iotort iotort.o \
-	libmeschach.a $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(DEFS) -fPIE -o iotort iotort.o \
+	-lmeschach -L. $(LIBS)
 mfuntort: mfuntort.o libmeschach.a
-	$(CC) $(CFLAGS) $(DEFS) -o mfuntort mfuntort.o \
-	libmeschach.a $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(DEFS) -fPIE -o mfuntort mfuntort.o \
+	-lmeschach -L. $(LIBS)
 tstmove: tstmove.o libmeschach.a
-	$(CC) $(CFLAGS) $(DEFS) -o tstmove tstmove.o \
-	libmeschach.a $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(DEFS) -fPIE -o tstmove tstmove.o \
+	-lmeschach -L. $(LIBS)
 tstpxvec: tstpxvec.o libmeschach.a
-	$(CC) $(CFLAGS) $(DEFS) -o tstpxvec tstpxvec.o \
-	libmeschach.a $(LIBS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(DEFS) -fPIE -o tstpxvec tstpxvec.o \
+	-lmeschach -L. $(LIBS)
 
