# Copyright 2024-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

RUST_MIN_VER="1.88.0"
CRATES="
	addr2line@0.25.1
	adler2@2.0.1
	aho-corasick@1.1.4
	android_system_properties@0.1.5
	anstream@0.6.21
	anstyle-parse@0.2.7
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.13
	anyhow@1.0.101
	assert_cmd@2.1.2
	assert_fs@1.1.3
	atomic-waker@1.1.2
	autocfg@1.5.0
	aws-lc-rs@1.15.3
	aws-lc-sys@0.36.0
	backtrace@0.3.76
	base64@0.22.1
	bitflags@2.10.0
	block2@0.6.2
	bstr@1.12.1
	built@0.8.0
	bumpalo@3.19.1
	bytes@1.11.1
	cc@1.2.53
	cesu8@1.1.0
	cfg-if@1.0.4
	cfg_aliases@0.2.1
	chrono@0.4.43
	clap@4.5.57
	clap_builder@4.5.57
	clap_complete@4.5.65
	clap_complete_nushell@4.5.10
	clap_derive@4.5.55
	clap_lex@0.7.7
	cli-table-derive@0.5.0
	cli-table@0.5.0
	cluFlock@1.2.7
	cmake@0.1.57
	colorchoice@1.0.4
	combine@4.6.7
	console@0.16.2
	core-foundation-sys@0.8.7
	core-foundation@0.10.1
	core-foundation@0.9.4
	crc32fast@1.5.0
	crossbeam-deque@0.8.6
	crossbeam-epoch@0.9.18
	crossbeam-utils@0.8.21
	csv-core@0.1.13
	csv@1.4.0
	ctrlc@3.5.1
	dialoguer@0.12.0
	difflib@0.4.0
	dirs-sys@0.5.0
	dirs@6.0.0
	dispatch2@0.3.0
	displaydoc@0.2.5
	doc-comment@0.3.4
	dunce@1.0.5
	either@1.15.0
	encode_unicode@1.0.0
	env_filter@0.1.4
	env_logger@0.11.8
	env_proxy@0.4.1
	equivalent@1.0.2
	errno@0.3.14
	fastrand@2.3.0
	filetime@0.2.26
	find-msvc-tools@0.1.8
	flate2@1.1.9
	float-cmp@0.10.0
	fnv@1.0.7
	foreign-types-shared@0.1.1
	foreign-types@0.3.2
	form_urlencoded@1.2.2
	fs_extra@1.3.0
	futures-channel@0.3.31
	futures-core@0.3.31
	futures-io@0.3.31
	futures-sink@0.3.31
	futures-task@0.3.31
	futures-util@0.3.31
	getrandom@0.2.17
	getrandom@0.3.4
	gimli@0.32.3
	globset@0.4.18
	globwalk@0.9.1
	h2@0.4.12
	hashbrown@0.16.1
	heck@0.5.0
	hermit-abi@0.5.2
	http-body-util@0.1.3
	http-body@1.0.1
	http@1.4.0
	httparse@1.10.1
	human-panic@2.0.6
	hyper-rustls@0.27.7
	hyper-tls@0.6.0
	hyper-util@0.1.19
	hyper@1.8.1
	iana-time-zone-haiku@0.1.2
	iana-time-zone@0.1.64
	icu_collections@2.1.1
	icu_locale_core@2.1.1
	icu_normalizer@2.1.1
	icu_normalizer_data@2.1.1
	icu_properties@2.1.2
	icu_properties_data@2.1.2
	icu_provider@2.1.1
	idna@1.1.0
	idna_adapter@1.2.1
	ignore@0.4.25
	indexmap@2.13.0
	indicatif@0.18.3
	indoc@2.0.7
	ipnet@2.11.0
	iri-string@0.7.10
	is-terminal@0.4.17
	is_terminal_polyfill@1.70.2
	itertools@0.14.0
	itoa@1.0.17
	jiff-static@0.2.18
	jiff@0.2.18
	jni-sys@0.3.0
	jni@0.21.1
	jobserver@0.1.34
	js-sys@0.3.85
	libc@0.2.180
	libredox@0.1.12
	linux-raw-sys@0.11.0
	litemap@0.8.1
	log@0.4.29
	lru-slab@0.1.2
	memchr@2.7.6
	miniz_oxide@0.8.9
	mio@1.1.1
	native-tls@0.2.14
	nix@0.30.1
	nix@0.31.1
	normalize-line-endings@0.3.0
	normpath@1.5.0
	ntapi@0.4.2
	num-traits@0.2.19
	numeric-sort@0.1.5
	objc2-core-foundation@0.3.2
	objc2-encode@4.1.0
	objc2-io-kit@0.3.2
	objc2@0.6.3
	object@0.37.3
	once_cell@1.21.3
	once_cell_polyfill@1.70.2
	openssl-macros@0.1.1
	openssl-probe@0.1.6
	openssl-probe@0.2.0
	openssl-sys@0.9.111
	openssl@0.10.75
	option-ext@0.2.0
	path-absolutize@3.1.1
	path-dedot@3.1.1
	percent-encoding@2.3.2
	pin-project-lite@0.2.16
	pin-utils@0.1.0
	pkg-config@0.3.32
	portable-atomic-util@0.2.4
	portable-atomic@1.13.0
	potential_utf@0.1.4
	ppv-lite86@0.2.21
	predicates-core@1.0.9
	predicates-tree@1.0.12
	predicates@3.1.3
	proc-macro2@1.0.105
	quinn-proto@0.11.13
	quinn-udp@0.5.14
	quinn@0.11.9
	quote@1.0.43
	r-efi@5.3.0
	rand@0.9.2
	rand_chacha@0.9.0
	rand_core@0.9.5
	redox_syscall@0.7.0
	redox_users@0.5.2
	regex-automata@0.4.13
	regex-syntax@0.8.8
	regex@1.12.3
	reqwest@0.13.1
	retry@2.2.0
	ring@0.17.14
	rustc-demangle@0.1.27
	rustc-hash@2.1.1
	rustix@1.1.3
	rustls-native-certs@0.8.3
	rustls-pki-types@1.14.0
	rustls-platform-verifier-android@0.1.1
	rustls-platform-verifier@0.6.2
	rustls-webpki@0.103.9
	rustls@0.23.36
	rustversion@1.0.22
	ryu@1.0.22
	same-file@1.0.6
	schannel@0.1.28
	security-framework-sys@2.15.0
	security-framework@2.11.1
	security-framework@3.5.1
	semver@1.0.27
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.149
	serde_spanned@1.0.4
	shell-words@1.1.1
	shellexpand@3.1.1
	shlex@1.3.0
	simd-adler32@0.3.8
	slab@0.4.11
	smallvec@1.15.1
	socket2@0.6.1
	stable_deref_trait@1.2.1
	strsim@0.11.1
	subtle@2.6.1
	syn@2.0.114
	sync_wrapper@1.0.2
	synstructure@0.13.2
	sysinfo@0.37.2
	tar@0.4.44
	tempfile@3.24.0
	termcolor@1.4.1
	terminal_size@0.4.3
	termtree@0.5.1
	thiserror-impl@1.0.69
	thiserror-impl@2.0.18
	thiserror@1.0.69
	thiserror@2.0.18
	tinystr@0.8.2
	tinyvec@1.10.0
	tinyvec_macros@0.1.1
	tokio-native-tls@0.3.1
	tokio-rustls@0.26.4
	tokio-util@0.7.16
	tokio@1.49.0
	toml@0.5.11
	toml@0.9.11+spec-1.1.0
	toml_datetime@0.7.5+spec-1.1.0
	toml_parser@1.0.6+spec-1.1.0
	toml_writer@1.0.6+spec-1.1.0
	tower-http@0.6.8
	tower-layer@0.3.3
	tower-service@0.3.3
	tower@0.5.3
	tracing-core@0.1.36
	tracing@0.1.44
	try-lock@0.2.5
	unicode-ident@1.0.22
	unicode-width@0.2.2
	unit-prefix@0.5.2
	untrusted@0.9.0
	url@2.5.8
	utf8_iter@1.0.4
	utf8parse@0.2.2
	uuid@1.19.0
	vcpkg@0.2.15
	wait-timeout@0.2.1
	walkdir@2.5.0
	want@0.3.1
	wasi@0.11.1+wasi-snapshot-preview1
	wasip2@1.0.2+wasi-0.2.9
	wasm-bindgen-futures@0.4.58
	wasm-bindgen-macro-support@0.2.108
	wasm-bindgen-macro@0.2.108
	wasm-bindgen-shared@0.2.108
	wasm-bindgen@0.2.108
	web-sys@0.3.85
	web-time@1.1.0
	webpki-root-certs@1.0.5
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.11
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-collections@0.2.0
	windows-collections@0.3.2
	windows-core@0.61.2
	windows-core@0.62.2
	windows-future@0.2.1
	windows-future@0.3.2
	windows-implement@0.60.2
	windows-interface@0.59.3
	windows-link@0.1.3
	windows-link@0.2.1
	windows-numerics@0.2.0
	windows-numerics@0.3.1
	windows-result@0.3.4
	windows-result@0.4.1
	windows-strings@0.4.2
	windows-strings@0.5.1
	windows-sys@0.45.0
	windows-sys@0.52.0
	windows-sys@0.60.2
	windows-sys@0.61.2
	windows-targets@0.42.2
	windows-targets@0.52.6
	windows-targets@0.53.5
	windows-threading@0.1.0
	windows-threading@0.2.1
	windows@0.61.3
	windows@0.62.2
	windows_aarch64_gnullvm@0.42.2
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_gnullvm@0.53.1
	windows_aarch64_msvc@0.42.2
	windows_aarch64_msvc@0.52.6
	windows_aarch64_msvc@0.53.1
	windows_i686_gnu@0.42.2
	windows_i686_gnu@0.52.6
	windows_i686_gnu@0.53.1
	windows_i686_gnullvm@0.52.6
	windows_i686_gnullvm@0.53.1
	windows_i686_msvc@0.42.2
	windows_i686_msvc@0.52.6
	windows_i686_msvc@0.53.1
	windows_x86_64_gnu@0.42.2
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnu@0.53.1
	windows_x86_64_gnullvm@0.42.2
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_gnullvm@0.53.1
	windows_x86_64_msvc@0.42.2
	windows_x86_64_msvc@0.52.6
	windows_x86_64_msvc@0.53.1
	winnow@0.7.14
	winres@0.1.12
	wit-bindgen@0.51.0
	writeable@0.6.2
	xattr@1.6.1
	yoke-derive@0.8.1
	yoke@0.8.1
	zerocopy-derive@0.8.33
	zerocopy@0.8.33
	zerofrom-derive@0.1.6
	zerofrom@0.1.6
	zeroize@1.8.2
	zerotrie@0.2.3
	zerovec-derive@0.11.2
	zerovec@0.11.5
	zmij@1.0.14
"

inherit cargo shell-completion toolchain-funcs

DESCRIPTION="Julia installer and version multiplexer"
HOMEPAGE="https://github.com/JuliaLang/juliaup"
SRC_URI="
	https://github.com/JuliaLang/juliaup/archive/v${PV}/${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD CDLA-Permissive-2.0 ISC MIT MPL-2.0 openssl
	Unicode-3.0
"
SLOT="0"
KEYWORDS="~amd64"

DOCS=( CHANGELOG.md README.md )

QA_FLAGS_IGNORED=".*"

src_test() {
	local mytestargs=(
		# The following tests require network access.
		--skip channel_selection
		--skip auto_install_valid_channel
		--skip end_to_end_manifest_selection
		--skip command_add
		--skip api_getconfig1
		--skip command_default
		--skip command_gc
		--skip command_initial_setup
		--skip command_link
		--skip alias
		--skip command_override
		--skip command_remove
		--skip command_update
	)
	cargo_src_test -- "${mytestargs[@]}"
}

src_install() {
	cargo_src_install
	einstalldocs

	if ! tc-is-cross-compiler; then
		einfo "generating shell completion files"

		"${ED}"/usr/bin/juliaup completions bash > "${T}/${PN}" || die
		dobashcomp "${T}/${PN}"

		"${ED}"/usr/bin/juliaup completions zsh > "${T}/_${PN}" || die
		dozshcomp "${T}/_${PN}"

		"${ED}"/usr/bin/juliaup completions fish > "${T}/${PN}.fish" || die
		dofishcomp "${T}/${PN}.fish"
	else
		ewarn "Shell completion files not installed! Install them manually with '${PN} completions --help'"
	fi
}
