PKGS = \
       libboinc \
       libboinc_api \
       libboinc_zip

REGEXP_OBJS = \
	regexp.o \
	regsub.o \
	regerror.o \
	regexp_memory.o \
	regexp_report.o

CXXFLAGS += $(shell pkg-config --cflags $(PKGS)) -I../..
LIBS     += $(shell pkg-config --libs $(PKGS))

boinc-wrapper: wrapper.o $(REGEXP_OBJS)
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -o $@ $^ $(LIBS) $(LDFLAGS)
