#!/sbin/openrc-run

# This section is kindly copied from display-manager-init
depend() {
	need localmount

	after bootmisc consolefont modules netmount
	after readahead-list ypbind autofs openvpn gpm lircmd
	after quota keymaps
	after elogind
	after sssd
	before alsasound

	use dbus xfs
}

start() {
	tty=7
	start-stop-daemon --start --background \
	--exec "/usr/bin/openvt" -- --console ${tty} --switch -- /usr/bin/lemurs

	eend $?
}
