name: repoman

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup repoman
      run: |
        python -m pip install --upgrade pip
        pip install lxml pyyaml
        wget -qO - "https://github.com/gentoo/portage/archive/portage-3.0.18.tar.gz" | tar xz
        sudo groupadd -g 250 portage
        sudo useradd -g portage -d /var/tmp/portage -s /bin/false -u 250 portage
    - name: Setup master gentoo repository
      run: |
        sudo mkdir -p /var/db/repos/gentoo /etc/portage /var/cache/distfiles
        wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | sudo tar xz -C /var/db/repos/gentoo --strip-components=1
        sudo wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
        sudo wget "https://gitweb.gentoo.org/proj/portage.git/plain/cnf/repos.conf" -O /etc/portage/repos.conf
        sudo ln -s /var/db/repos/gentoo/profiles/default/linux/amd64/17.1 /etc/portage/make.profile
    - name: Update portage
      run: |
        python3 portage-portage-3.0.18/bin/emerge --sync
        python3 portage-portage-3.0.18/bin/emerge -1 sys-apps/portage    
    - name: Test with repoman
      run: |
        python3 portage-portage-3.0.18/repoman/bin/repoman full -dx
