# Copyright 2024-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.4

EAPI=8

CRATES="
"

RUST_MIN_VER="1.82.0"

inherit cargo

DESCRIPTION="blazing fast terminal-ui for git"
HOMEPAGE="https://github.com/gitui-org/gitui"
SRC_URI="
	https://github.com/gitui-org/gitui/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	https://github.com/pastalian/distfiles/releases/download/${P}/${P}-crates.tar.xz
	${CARGO_CRATE_URIS}
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD-2 BSD CC0-1.0 ISC MIT MPL-2.0 Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

RDEPEND="
	>=dev-libs/libgit2-1.9.2:0/1.9
	dev-libs/openssl:=
	net-libs/libssh2
"
DEPEND="${RDEPEND}"

DOCS=( {README,KEY_CONFIG,THEMES}.md vim_style_key_config.ron )
QA_FLAGS_IGNORED="usr/bin/gitui"

src_configure() {
	# Use system library
	export LIBSSH2_SYS_USE_PKG_CONFIG=1
	export LIBGIT2_NO_VENDOR=1

	local myfeatures=(
		ghemoji
		regex-fancy
		trace-libgit
	)
	cargo_src_configure --no-default-features
}

src_install() {
	cargo_src_install

	einstalldocs
}

pkg_postinst() {
	elog "Example vim style key config is installed in '${EROOT}/usr/share/doc/${PF}'."
	elog "To use it, copy the content into '\$XDG_CONFIG_HOME/gitui/key_configs.ron'."
}
