# Copyright 2025-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

RUST_MIN_VER="1.88.0"

# apply-crates-fixes start
LLVM_COMPAT=( {19..22} )
# apply-crates-fixes end

CRATES="
	adler2@2.0.1
	aho-corasick@1.1.4
	aligned-vec@0.6.4
	aligned@0.4.3
	allocator-api2@0.2.21
	android_system_properties@0.1.5
	ansi_colours@1.2.3
	anstream@0.6.21
	anstyle-parse@0.2.7
	anstyle-query@1.1.5
	anstyle-wincon@3.0.7
	anstyle@1.0.13
	anyhow@1.0.100
	arbitrary@1.4.1
	arg_enum_proc_macro@0.3.4
	arrayvec@0.7.6
	as-slice@0.2.1
	atomic@0.6.1
	autocfg@1.5.0
	av-scenechange@0.14.1
	av1-grain@0.2.5
	avif-serialize@0.8.6
	base64@0.22.1
	bit-set@0.5.3
	bit-vec@0.6.3
	bit_field@0.10.3
	bitflags@1.3.2
	bitflags@2.10.0
	bitstream-io@4.9.0
	block-buffer@0.10.4
	bon-macros@3.8.1
	bon@3.8.1
	built@0.8.0
	bumpalo@3.19.0
	bytemuck@1.24.0
	byteorder-lite@0.1.0
	castaway@0.2.4
	cc@1.2.48
	cfg-if@1.0.4
	cfg_aliases@0.2.1
	chrono@0.4.42
	clap@4.5.53
	clap_builder@4.5.53
	clap_complete@4.5.62
	clap_derive@4.5.49
	clap_lex@0.7.6
	clap_mangen@0.2.31
	color_quant@1.1.0
	colorchoice@1.0.4
	compact_str@0.9.0
	console@0.16.1
	convert_case@0.10.0
	core-foundation-sys@0.8.7
	core2@0.4.0
	cpufeatures@0.2.17
	crc32fast@1.5.0
	crossbeam-channel@0.5.15
	crossbeam-deque@0.8.6
	crossbeam-epoch@0.9.18
	crossbeam-queue@0.3.12
	crossbeam-utils@0.8.21
	crossbeam@0.8.4
	crossterm@0.29.0
	crossterm_winapi@0.9.1
	crunchy@0.2.3
	crypto-common@0.1.7
	csscolorparser@0.6.2
	darling@0.20.11
	darling@0.21.3
	darling_core@0.20.11
	darling_core@0.21.3
	darling_macro@0.20.11
	darling_macro@0.21.3
	deltae@0.3.2
	deranged@0.5.5
	derive_builder@0.20.2
	derive_builder_core@0.20.2
	derive_builder_macro@0.20.2
	derive_more-impl@2.1.1
	derive_more@2.1.1
	dialoguer@0.12.0
	digest@0.10.7
	displaydoc@0.2.5
	document-features@0.2.12
	dyn-clone@1.0.19
	either@1.15.0
	encode_unicode@1.0.0
	enum-map-derive@0.17.0
	enum-map@2.7.3
	env_home@0.1.0
	equator-macro@0.4.2
	equator@0.4.2
	equivalent@1.0.2
	errno@0.3.14
	euclid@0.22.11
	exr@1.74.0
	fancy-regex@0.11.0
	fax@0.2.6
	fax_derive@0.2.0
	fdeflate@0.3.7
	file-id@0.2.3
	filedescriptor@0.8.3
	find-msvc-tools@0.1.5
	finl_unicode@1.4.0
	fixedbitset@0.4.2
	flate2@1.1.5
	flexi_logger@0.31.7
	fnv@1.0.7
	foldhash@0.2.0
	form_urlencoded@1.2.2
	fsevent-sys@4.1.0
	futures-core@0.3.31
	futures-macro@0.3.31
	futures-task@0.3.31
	futures-timer@3.0.3
	futures-util@0.3.31
	generic-array@0.14.7
	getrandom@0.3.4
	gif@0.14.1
	glob@0.3.2
	half@2.7.1
	hashbrown@0.12.3
	hashbrown@0.16.1
	heck@0.5.0
	hex@0.4.3
	iana-time-zone-haiku@0.1.2
	iana-time-zone@0.1.64
	icu_collections@2.0.0
	icu_locale_core@2.0.0
	icu_normalizer@2.0.0
	icu_normalizer_data@2.0.0
	icu_properties@2.0.1
	icu_properties_data@2.0.1
	icu_provider@2.0.0
	ident_case@1.0.1
	idna@1.1.0
	idna_adapter@1.2.1
	image-webp@0.2.4
	image@0.25.9
	imgref@1.12.0
	indexmap@1.9.3
	indexmap@2.12.1
	indoc@2.0.7
	inotify-sys@0.1.5
	inotify@0.11.0
	instability@0.3.10
	interpolate_name@0.2.4
	is_terminal_polyfill@1.70.2
	itertools@0.13.0
	itertools@0.14.0
	itoa@1.0.15
	jobserver@0.1.34
	js-sys@0.3.77
	kasuari@0.4.11
	kqueue-sys@1.0.4
	kqueue@1.1.1
	lab@0.11.0
	lazy_static@1.5.0
	lebe@0.5.3
	libc@0.2.178
	libfuzzer-sys@0.4.9
	line-clipping@0.3.5
	linux-raw-sys@0.11.0
	litemap@0.8.0
	litrs@1.0.0
	lock_api@0.4.14
	log@0.4.29
	loop9@0.1.5
	lru@0.16.2
	mac_address@1.1.8
	maybe-rayon@0.1.1
	memchr@2.7.6
	memmem@0.1.1
	memoffset@0.9.1
	minimal-lexical@0.2.1
	miniz_oxide@0.8.9
	mio@1.1.1
	moxcms@0.7.11
	new_debug_unreachable@1.0.6
	nix@0.29.0
	nom@7.1.3
	nom@8.0.0
	noop_proc_macro@0.3.0
	notify-debouncer-full@0.6.0
	notify-types@2.0.0
	notify@8.2.0
	ntapi@0.4.1
	nu-ansi-term@0.50.3
	num-bigint@0.4.6
	num-conv@0.1.0
	num-derive@0.4.2
	num-integer@0.1.46
	num-rational@0.4.2
	num-traits@0.2.19
	num_threads@0.1.7
	objc2-core-foundation@0.3.1
	objc2-io-kit@0.3.1
	once_cell@1.21.3
	ordered-float@4.6.0
	parking_lot@0.12.5
	parking_lot_core@0.9.12
	paste@1.0.15
	pastey@0.1.1
	percent-encoding@2.3.2
	pest@2.8.4
	pest_derive@2.8.4
	pest_generator@2.8.4
	pest_meta@2.8.4
	phf@0.11.3
	phf_codegen@0.11.3
	phf_generator@0.11.3
	phf_macros@0.11.3
	phf_shared@0.11.3
	pin-project-lite@0.2.16
	pin-utils@0.1.0
	png@0.18.0
	portable-atomic@1.12.0
	potential_utf@0.1.2
	powerfmt@0.2.0
	ppv-lite86@0.2.21
	prettyplease@0.2.32
	proc-macro-crate@3.3.0
	proc-macro2@1.0.103
	profiling-procmacros@1.0.17
	profiling@1.0.17
	pxfm@0.1.27
	qoi@0.4.1
	quick-error@2.0.1
	quote@1.0.42
	r-efi@5.2.0
	rand@0.8.5
	rand@0.9.2
	rand_chacha@0.9.0
	rand_core@0.6.4
	rand_core@0.9.3
	ratatui-core@0.1.0
	ratatui-crossterm@0.1.0
	ratatui-macros@0.7.0
	ratatui-termwiz@0.1.0
	ratatui-widgets@0.3.0
	ratatui@0.30.0
	rav1e@0.8.1
	ravif@0.12.0
	rayon-core@1.13.0
	rayon@1.11.0
	redox_syscall@0.5.11
	ref-cast-impl@1.0.25
	ref-cast@1.0.25
	regex-automata@0.4.13
	regex-syntax@0.8.8
	regex@1.12.2
	relative-path@1.9.3
	rgb@0.8.52
	roff@0.2.2
	ron@0.12.0
	rstest@0.26.1
	rstest_macros@0.26.1
	rustc_version@0.4.1
	rustix@1.1.3
	rustversion@1.0.22
	ryu@1.0.20
	same-file@1.0.6
	schemars@0.9.0
	schemars@1.1.0
	scopeguard@1.2.0
	semver@1.0.27
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.147
	serde_path_to_error@0.1.20
	serde_with@3.16.1
	serde_with_macros@3.16.1
	sha2@0.10.9
	shell-words@1.1.0
	shlex@1.3.0
	signal-hook-mio@0.2.5
	signal-hook-registry@1.4.7
	signal-hook@0.3.18
	simd-adler32@0.3.7
	simd_helpers@0.1.0
	siphasher@1.0.1
	slab@0.4.11
	smallvec@1.15.1
	smawk@0.3.2
	stable_deref_trait@1.2.1
	static_assertions@1.1.0
	strsim@0.11.1
	strum@0.27.2
	strum_macros@0.27.1
	syn@1.0.109
	syn@2.0.111
	synstructure@0.13.2
	sysinfo@0.37.2
	terminfo@0.9.0
	termios@0.3.3
	termwiz@0.23.3
	test-case-core@3.3.1
	test-case-macros@3.3.1
	test-case@3.3.1
	textwrap@0.16.2
	thiserror-impl@1.0.69
	thiserror-impl@2.0.17
	thiserror@1.0.69
	thiserror@2.0.17
	tiff@0.10.3
	time-core@0.1.6
	time-macros@0.2.24
	time@0.3.44
	tinystr@0.8.1
	toml_datetime@0.6.11
	toml_edit@0.22.27
	typeid@1.0.3
	typenum@1.19.0
	ucd-trie@0.1.7
	unicase@2.8.1
	unicode-ident@1.0.22
	unicode-linebreak@0.1.5
	unicode-segmentation@1.12.0
	unicode-truncate@2.0.0
	unicode-width@0.2.0
	unicode-xid@0.2.6
	url@2.5.7
	utf8_iter@1.0.4
	utf8parse@0.2.2
	uuid@1.19.0
	v_frame@0.3.9
	vergen-gitcl@1.0.8
	vergen-lib@0.1.6
	vergen@9.0.6
	version_check@0.9.5
	vtparse@0.6.2
	walkdir@2.5.0
	wasi@0.11.0+wasi-snapshot-preview1
	wasip2@1.0.1+wasi-0.2.4
	wasm-bindgen-backend@0.2.100
	wasm-bindgen-macro-support@0.2.100
	wasm-bindgen-macro@0.2.100
	wasm-bindgen-shared@0.2.100
	wasm-bindgen@0.2.100
	weezl@0.1.12
	wezterm-bidi@0.2.3
	wezterm-blob-leases@0.1.1
	wezterm-color-types@0.3.0
	wezterm-dynamic-derive@0.1.1
	wezterm-dynamic@0.2.1
	wezterm-input-types@0.1.0
	which@8.0.0
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.9
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-collections@0.2.0
	windows-core@0.61.0
	windows-future@0.2.0
	windows-implement@0.60.0
	windows-interface@0.59.1
	windows-link@0.1.1
	windows-link@0.2.0
	windows-numerics@0.2.0
	windows-result@0.3.2
	windows-strings@0.4.0
	windows-sys@0.59.0
	windows-sys@0.60.2
	windows-sys@0.61.0
	windows-targets@0.52.6
	windows-targets@0.53.4
	windows@0.61.1
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_gnullvm@0.53.1
	windows_aarch64_msvc@0.52.6
	windows_aarch64_msvc@0.53.1
	windows_i686_gnu@0.52.6
	windows_i686_gnu@0.53.1
	windows_i686_gnullvm@0.52.6
	windows_i686_gnullvm@0.53.1
	windows_i686_msvc@0.52.6
	windows_i686_msvc@0.53.1
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnu@0.53.1
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_gnullvm@0.53.1
	windows_x86_64_msvc@0.52.6
	windows_x86_64_msvc@0.53.1
	winnow@0.7.14
	winsafe@0.0.19
	wit-bindgen@0.46.0
	writeable@0.6.1
	y4m@0.8.0
	yoke-derive@0.8.0
	yoke@0.8.0
	zerocopy-derive@0.8.31
	zerocopy@0.8.31
	zerofrom-derive@0.1.6
	zerofrom@0.1.6
	zerotrie@0.2.2
	zerovec-derive@0.11.1
	zerovec@0.11.2
	zmij@0.1.9
	zune-core@0.4.12
	zune-core@0.5.0
	zune-inflate@0.2.54
	zune-jpeg@0.4.21
	zune-jpeg@0.5.7
"

# apply-crates-fixes start
inherit llvm-r2
# apply-crates-fixes end

inherit cargo shell-completion desktop xdg

DESCRIPTION="A beautiful and configurable TUI client for MPD"
HOMEPAGE="https://mierak.github.io/rmpc/"
LICENSE="BSD"

# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD-2 BSD CC0-1.0 ISC LGPL-3+ MIT UoI-NCSA Unicode-3.0
	Unicode-DFS-2016 WTFPL-2 ZLIB
"

if [[ "${PV}" == *9999* ]]; then
	inherit git-r3
	EGIT_REPO_URI="https://github.com/mierak/${PN}"
else
	SRC_URI="https://github.com/mierak/${PN}/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
		${CARGO_CRATE_URIS}"
	KEYWORDS="~amd64"
	RESTRICT="mirror"
fi

SLOT="0"
# apply-crates-fixes start
DEPEND="
	$(llvm_gen_dep 'llvm-runtimes/compiler-rt-sanitizers:${LLVM_SLOT}[libfuzzer]')
"
BDEPEND="
	$(llvm_gen_dep 'llvm-core/clang:${LLVM_SLOT}')
	virtual/pkgconfig
"
# apply-crates-fixes end

DOCS=( README.md CHANGELOG.md )

src_unpack() {
	if [[ "${PV}" == *9999* ]];then
		git-r3_src_unpack
		cargo_live_src_unpack
	else
		cargo_src_unpack
	fi
}

# apply-crates-fixes start
src_compile(){
	CUSTOM_LIBFUZZER_PATH="$(clang --print-file-name "libclang_rt.fuzzer-${CHOST%%-*}.a" )"
	[[ -f "${CUSTOM_LIBFUZZER_PATH}" ]] || die "trying to set CUSTOM_LIBFUZZER_PATH failed"
	export CUSTOM_LIBFUZZER_PATH
	cargo_src_compile
}
# apply-crates-fixes end

src_install() {
	cargo_src_install
	einstalldocs
	doman target/man/*
	newbashcomp target/completions/"${PN}".bash "${PN}"
	dozshcomp target/completions/_"${PN}"
	dofishcomp target/completions/"${PN}".fish
	domenu assets/"${PN}".desktop
}
